CREATE TABLE [dbo].[Acc_Req_Det]
(
	[AccReqMasID] INT NULL ,
	AccReqDetID int IDENTITY(1,1) NOT NULL,
	GarColorID int NULL,
	GarSizeID int NULL,
	GarQty decimal(14,3) NOT NULL DEFAULT 0,
	AccColorID int NULL,
	AccSizeID int NULL,
	QtyPerPiece decimal(9,3) NULL,
	TotalQty decimal(14,3) NOT NULL DEFAULT 0,
	BOMQty decimal(14,3) NOT NULL DEFAULT 0,
	LockRow char(1) NULL,
	Item_Remarks varchar(200) NULL,
	PColorID int NULL,
	PQty decimal(14,3) NULL,
	ItemCode varchar(30) NULL,
	Rate numeric(18,4) NULL,
	CONSTRAINT [PK_Acc_Req_Det] PRIMARY KEY ([AccReqDetID]), 
	CONSTRAINT [FK_AccReqDetColor] FOREIGN KEY ([AccColorID]) REFERENCES [Color]([Colorid]),
	CONSTRAINT [FK_AccReqMasRef] FOREIGN KEY ([AccReqMasID]) REFERENCES Acc_Req_Mas([AccReqMasID]),
	CONSTRAINT [FK_AccReqDetSize] FOREIGN KEY (AccSizeID) REFERENCES Size([SizeId]),
	CONSTRAINT [FK_AccReqDetGarColor] FOREIGN KEY (GarColorID) REFERENCES [Color]([Colorid]),
	CONSTRAINT [FK_AccReqDetGarSize] FOREIGN KEY (GarSizeID) REFERENCES Size([SizeId]),
)
