CREATE TABLE [dbo].[Con_Plan_Amend]
(
	[Con_PlanAmndId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Con_PlanID] INT  NULL ,
	[CompSlNo] [int]  NULL,
	[CPlanSlNo] [int]  NULL,
	[PlanID] [int]  NULL,
	[ColorID] [int] NOT NULL,
	[SizeId] [int] NOT NULL,
	[Prdn_Qty] [int] NOT NULL,
	[Length] [decimal](9, 2) NOT NULL DEFAULT (0),
	[Width] [decimal](9, 2) NOT NULL DEFAULT (0),
	[GSM] [decimal](10, 3) NOT NULL DEFAULT (0),
	[Grammage] [decimal](10, 3) NULL,
	[Weight] [decimal](10, 3) NOT NULL,
	[Wmetres] [decimal](10, 2) NOT NULL DEFAULT (0),
	[ActualFabricWidth] [numeric](14, 3) NULL,
	[GreyWidthID] [int] NULL,
	[FinishWidthID] [int] NULL,
	[ComponentID] [int] NULL,
	LengthAllow [decimal](9, 2) NOT NULL DEFAULT (0),
	WidthAllow [decimal](9, 2) NOT NULL DEFAULT (0),
	Pattern [decimal](9, 2) NOT NULL DEFAULT (0),
	CONSTRAINT [fk_Con_Plan_am_ColorID] FOREIGN KEY([ColorID]) REFERENCES [dbo].[Color] ([Colorid]),
	CONSTRAINT [fk_Con_Plan_am_SizeId] FOREIGN KEY([SizeId]) REFERENCES [dbo].[Size] ([SizeId]),
	CONSTRAINT [fk_Con_Plan_am_GreyWidthID] FOREIGN KEY([GreyWidthID]) REFERENCES [dbo].[Size] ([SizeId]),
	CONSTRAINT [fk_Con_Plan_am_FinishWidthID] FOREIGN KEY([FinishWidthID]) REFERENCES [dbo].[Size] ([SizeId]),
	--CONSTRAINT [fk_Con_Plan_am_PlanID] FOREIGN KEY([PlanID]) REFERENCES [dbo].[Planning_Mas] ([PlanID]),
	CONSTRAINT [FK_Con_Plan_am_ItemComp] FOREIGN KEY ([ComponentID]) REFERENCES [Item]([ItemId])
)
