CREATE TABLE [dbo].[Cost_Defn_BOM]
(
    [Cost_Defn_id] [int] NOT NULL ,
	[Cost_Defn_BOMid] [int] IDENTITY(1,1) NOT NULL primary key,
	[Processid] [int] NULL,
	[Itemid] [int] NULL,
	[Colorid] [int] NULL,
	[Sizeid] [int] NULL,
	[Quantity] [numeric](14, 3) NULL  DEFAULT (0),
	[Rate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[UOMid] [int] NULL,
	[Access_Type] [varchar](1) NULL,
	[Actual_Qty] [numeric](14, 3) NOT NULL  DEFAULT (0),
	[Actual_Rate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[CurrencyID] [int] NULL,
	[ExRate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[CurrencyRate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[AppRate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[AppCurrencyRate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[DisplayOption] [char](1) NULL,
	[AppQty] [numeric](12, 3) NOT NULL  DEFAULT (0),
	[lUpdateDate] [datetime] NULL,
	[FirstRate] [numeric](15, 5) NOT NULL  DEFAULT (0),
	[IsSecQty] [varchar](1) NOT NULL DEFAULT ('N'),
	[SecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[AppSecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[ActualSecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[Invoice_Qty] [numeric](14, 3) NULL,
	[Invoice_Rate] [numeric](14, 3) NULL,
	[Invoice_SecQty] [numeric](14, 3) NULL,
	[ReturnQty] [numeric](14, 3) NULL,

	[SupplierId] INT NULL, 
    CONSTRAINT [costBOM_currency] FOREIGN KEY([CurrencyID]) REFERENCES [dbo].[Currency] ([CurrencyId]),
	CONSTRAINT [fk_cost_defn_bom_colorid] FOREIGN KEY([Colorid]) REFERENCES [dbo].[Color] ([Colorid]),
	CONSTRAINT [fk_cost_defn_bom_Cost_Defn_id] FOREIGN KEY([Cost_Defn_id]) REFERENCES [dbo].[Cost_Defn_Mas] ([Cost_Defn_id]),
	CONSTRAINT [fk_cost_defn_bom_itemid] FOREIGN KEY([Itemid]) REFERENCES [dbo].[Item] ([ItemId]),
	CONSTRAINT [fk_cost_defn_bom_processid] FOREIGN KEY([Processid]) REFERENCES [dbo].[Process] ([ProcessId]),
	CONSTRAINT [fk_cost_defn_bom_sizeid] FOREIGN KEY([Sizeid]) REFERENCES [dbo].[Size] ([SizeId]),
	CONSTRAINT [fk_cost_defn_bom_UOMid] FOREIGN KEY([UOMid]) REFERENCES [dbo].[Unit_of_measurement] ([UomId]),
	CONSTRAINT [chk_SecQtyType] CHECK  (([IsSecQty] = 'Y' or [IsSecQty] = 'N')),



)
