CREATE TABLE [dbo].[Fabric_Plan]
(
	
	[FPlanId] [int] IDENTITY(1,1) NOT NULL,
	[CompSlNo] [int] NOT NULL,
	[PlanID] [int] NOT NULL,
	[ColorID] [int] NOT NULL,
	[SizeId] [int] NOT NULL,
	[Prdn_Qty] [int] NOT NULL,
	[Fabric_Req] [decimal](12, 3) NOT NULL,
	[Grammage] [decimal](10, 3) NOT NULL,
	[Woven_Req_InMtrs] [decimal](10, 2) NOT NULL,
	[LossGain] [decimal](5, 2) NOT NULL DEFAULT (0.00),
	[FabricId] [int] NOT NULL,
	[Fabric_type] [char](1) NOT NULL,
	[Fab_WidthId] [int] NOT NULL,
	[Table_WidthID] [int] NOT NULL,
	[BaseColorID] [int] NOT NULL,
	[BColorPur_Qty] [decimal](10, 3) NOT NULL,
	[FinishColorID] [int] NOT NULL,
	[FColorPur_Qty] [decimal](10, 3) NULL,
	[PrintColorId] [int] NULL,
	[EntryDate] [datetime] NOT NULL DEFAULT ('2005-01-01'),
	[Knit_GSM] [varchar](10) NULL,
	[Fin_GSM] [varchar](10) NULL,
	[Loop_Len] [varchar](10) NULL,
	[Texture] [varchar](40) NULL,
	[Content] [varchar](40) NULL,
	[Gauge] [varchar](40) NOT NULL DEFAULT (''), 
    CONSTRAINT [PK_Fabric_Plan] PRIMARY KEY ([FPlanId]),
    CONSTRAINT [FK_Fabric_Plan_Color] FOREIGN KEY ([ColorID]) REFERENCES [Color]([Colorid]),
	   CONSTRAINT [FK_Fabric_Plan_BColor] FOREIGN KEY ([BaseColorID]) REFERENCES [Color]([Colorid]),
	      CONSTRAINT [FK_Fabric_Plan_FColor] FOREIGN KEY ([FinishColorID]) REFERENCES [Color]([Colorid]),
		     CONSTRAINT [FK_Fabric_Plan_PColor] FOREIGN KEY ([PrintColorId]) REFERENCES [Color]([Colorid]),
			   CONSTRAINT [FK_Fabric_Plan_Item] FOREIGN KEY ([FabricId]) REFERENCES [Item]([Itemid]),
			    CONSTRAINT [FK_Fabric_Plan_Size] FOREIGN KEY ([SizeId]) REFERENCES [Size]([Sizeid]),
				CONSTRAINT [FK_Fabric_Plan_Planning_Mas] FOREIGN KEY ([PlanID]) REFERENCES [Planning_Mas]([PlanID]), 
    CONSTRAINT [CK_Fabric_Plan_Fabric_type] CHECK (([fabric_type] = 'K' or [fabric_type] = 'W' or [fabric_type] = 'P'))
)
