CREATE TABLE [dbo].[Job_Recpt_Mas]
(
	[JobRecptId] [int] IDENTITY(1,1) NOT NULL,
	[JobRecptNo] [varchar](20) NOT NULL,
	[JobRecptDate] [datetime] NOT NULL,
	[DcNo] [varchar](20) NOT NULL,
	[DcDate] [datetime] NOT NULL,
	[SupplierId] [int] NOT NULL,
	[Unit_Or_Other] [varchar](1) NOT NULL DEFAULT ('P'),
	[Job_Ord_No] [varchar](20) NOT NULL DEFAULT (''),
	[Companyid] [int] NULL,
	[Order_No] [varchar](20) NULL,
	[styleid] [int] NULL,
	[Remarks] [varchar](1000) NULL DEFAULT (null),
	[Tostoreid] [int] NULL DEFAULT (null),
	[QualityMade] [char](1) NULL,
	[QualityRemarks] [varchar](250) NULL,
	[QualityDate] [datetime] NULL,
	[DispatchNo] [varchar](20) NULL,
	[Buy_Ord_Ship] [varchar](8) NULL,
	[ShipmentMode] [int] NULL,
	[SystemID] [int] NULL,
	[DocRefNo] [varchar](50) NULL,
	[DocRefDate] [datetime] NULL,
	[InvRefNo] [varchar](50) NULL,
	[InvRefDate] [datetime] NULL,
	[ShipmentType] [char](1) NULL,
	[CreatedBy] [int] NULL, 
    CONSTRAINT [PK_Job_Recpt_Mas] PRIMARY KEY ([JobRecptId]), 
    --CONSTRAINT [FK_Job_Recpt_Mas_Buy_Ord_Ship] FOREIGN KEY ([Buy_Ord_Ship]) REFERENCES [Buy_Ord_Ship]([buy_ord_ship]),
	CONSTRAINT [FK_Job_Recpt_Mas_company] FOREIGN KEY ([Companyid]) REFERENCES [company]([Companyid]),
	CONSTRAINT [FK_Job_Recpt_Mas_ShipmentMode] FOREIGN KEY ([ShipmentMode]) REFERENCES [Mode_Of_Shipment]([Mode_of_Shipmentid]),
	CONSTRAINT [FK_Job_Recpt_Mas_System] FOREIGN KEY ([SystemId]) REFERENCES [ShipmentSystem]([Systemid]),
	CONSTRAINT [FK_Job_Recpt_Mas_employee] FOREIGN KEY ([CreatedBy]) REFERENCES [employee]([employeeid]),
	CONSTRAINT [FK_Job_Recpt_Mas_Style] FOREIGN KEY ([styleid]) REFERENCES [StyleHeader]([styleid]),
	CONSTRAINT [FK_Job_Recpt_Mas_StoreUnit] FOREIGN KEY ([Tostoreid]) REFERENCES [StoreUnit]([StoreUnitID]), 
    CONSTRAINT [CK_Job_Recpt_Mas_ShipmentType] CHECK (([ShipmentType] = 'P' or [ShipmentType] = 'F')),
	 CONSTRAINT [CK_Job_Recpt_Mas_Unit_Or_Other] CHECK (([Unit_Or_Other] = 'P' or [Unit_Or_Other] = 'S'))
)
