CREATE TABLE [dbo].[Job_Ord_BomDet]
(
    [Job_Ord_BOMDetid] [int] IDENTITY(1,1) NOT NULL primary key,
	[Job_Ord_BOMid] [int] NOT NULL,
	[Itemid] [int] NULL,
	[Colorid] [int] NULL,
	[Sizeid] [int] NULL,
	[UOMid] [int] NOT NULL,
	[Prg_qty] [numeric](14, 3) NOT NULL CHECK (([Prg_qty] >= 0)) DEFAULT (0),
	[Order_qty] [numeric](14, 3) NOT NULL CHECK (([Order_qty] >= 0)) DEFAULT (0),
	[Received_qty] [numeric](14, 3) NOT NULL  CHECK  (([Received_Qty] >= 0)) DEFAULT (0),
	[Issue_qty] [numeric](14, 3) NOT NULL CHECK (([Issue_qty] >= 0)) DEFAULT (0),
	[BOM_qty] [numeric](14, 3) NOT NULL CHECK  (([BOM_qty] >= 0)) DEFAULT (0),
	[Pur_UOMid] [int] NULL,
	[ToPurUOM] [numeric](10, 3) NULL DEFAULT (1),
	[head_office] [bit] NULL,
	[purchase_thru] [varchar](1) NULL,
	[Conv_Mode] [varchar](1) NULL CHECK  (([conv_mode] = 'M' or [conv_mode] = 'D')) DEFAULT ('M') ,
	[Adjust_Qty] [numeric](14, 3) NULL  DEFAULT (0.000),
	[PurForJob] [varchar](1) NULL DEFAULT ('N'),
	[Debit_qty] [numeric](14, 3) NULL CHECK  (([Debit_Qty] >= 0))  DEFAULT (0),
	[Transfer_In] [numeric](14, 3) NOT NULL CHECK  (([Transfer_In] >= 0)) DEFAULT (0.000),
	[Transfer_Out] [numeric](14, 3) NOT NULL CHECK  (([Transfer_Out] >= 0))  DEFAULT (0.000),
	[Cancelled_Qty] [numeric](14, 3) NULL CHECK  (([Cancelled_Qty] >= 0)) DEFAULT (0),
	[BOMDiff_Qty] [numeric](14, 3) NULL DEFAULT (0),
	[Cancel_Qty] [numeric](14, 3) NOT NULL CHECK  (([Cancel_Qty] >= 0)) DEFAULT (0),
	[EntryDate] [datetime] NULL DEFAULT (getdate()),
	[Semi_finished_item] [varchar](2) NULL,
	[CSP] [varchar](1) NOT NULL DEFAULT ('N'),
	[ProcessInput] [varchar](1) NULL,
	[AltItem] [char](1) NOT NULL DEFAULT ('N'),
	[ItemRemarks] [varchar](50) NOT NULL DEFAULT ('') ,
	[ItemClosure] [char](1) NOT NULL DEFAULT ('N'),
	[ReturnQty] [numeric](14, 3) NULL CHECK (([ReturnQty] >= 0)) DEFAULT (0),
	[StockIn] [numeric](14, 3) NULL  CHECK  (([StockIn] >= 0)) DEFAULT (0),
	[StockOut] [numeric](14, 3) NOT NULL CHECK  (([StockOut] >= 0)) DEFAULT (0),

	 CONSTRAINT [fk_Job_ord_bomdet_buy_ord_bomid] FOREIGN KEY([Job_Ord_BOMid])REFERENCES [dbo].[Job_Ord_BOMMas] ([Job_Ord_BOMid]),
	 CONSTRAINT [Fk_Job_Ord_BOMDet_Colorid] FOREIGN KEY([Colorid])REFERENCES [dbo].[Color] ([Colorid]),
	 CONSTRAINT [Fk_Job_ord_bomdet_pur_uomid] FOREIGN KEY([Pur_UOMid])REFERENCES [dbo].[Unit_of_measurement] ([UomId]),
	 CONSTRAINT [Fk_Job_Ord_BOMDet_Sizeid] FOREIGN KEY([Sizeid])REFERENCES [dbo].[Size] ([SizeId]),
	 CONSTRAINT [Fk_Job_ord_bomdet_uomid] FOREIGN KEY([UOMid])REFERENCES [dbo].[Unit_of_measurement] ([UomId]),
	 CONSTRAINT [Fk_Job_Itemid] FOREIGN KEY([Itemid])REFERENCES [dbo].[Item] ([ItemId]),
)
