CREATE TABLE [dbo].[Planning_Mas]
(
    [PlanID] [int] IDENTITY(1,1) NOT NULL, 
	[CompanyID] [int] NOT NULL,
	[Buy_Ord_MasId] [int] NOT NULL,
	[Order_No] [varchar](20) NOT NULL,
	[StyleID] [int] NOT NULL,
	[ItemID] [int] NOT NULL,
	[Con_Plan] [char](1) NOT NULL DEFAULT ('N'),
	[Fabric_Plan] [char](1) NOT NULL DEFAULT ('N'),
	[Yarn_Plan] [char](1) NOT NULL DEFAULT ('N'),
	[Acc_Plan] [char](1) NOT NULL DEFAULT ('N'),
	[Pack_Plan] [char](1) NOT NULL,
	[Fab_plan_Remarks] [varchar](150) NULL,
	[CreatedBy] [int] NULL,
	[IsApproved] [char](1) NULL,
	[LockPlanning] [bit] NULL,
	[LockCon] [int] NULL,
	[LockFab] [int] NULL,
	[LockYarn] [int] NULL,
	[LockAccs] [int] NULL,
	[LockPack] [int] NULL,
	[ModifyBy] [int] null,
	[Modify_Date] [datetime] NULL,
	[PA] [char](1) NULL DEFAULT ('P'),
    CONSTRAINT [PK_Planning_Mas] PRIMARY KEY ([PlanID]),
	CONSTRAINT [FK_Planning_Mas_Company] FOREIGN KEY ([CompanyID]) REFERENCES [Company]([CompanyId]), 
    CONSTRAINT [FK_Planning_Mas_Employee] FOREIGN KEY([CreatedBy])REFERENCES [dbo].[Employee] ([EmployeeId]), 
	CONSTRAINT [FK_Planning_Mas_Item] FOREIGN KEY([ItemID])REFERENCES [dbo].[Item] ([ItemId]), 
	CONSTRAINT [FK_Planning_Mas_Style] FOREIGN KEY([StyleID])REFERENCES [dbo].[StyleHeader] ([StyleId]), 
    CONSTRAINT [FK_Planning_Mas_Buy_Ord_Mas] FOREIGN KEY ([Buy_Ord_MasId]) REFERENCES [Buy_Ord_Mas]([Buy_Ord_MasId]),
	CONSTRAINT [FK_Planning_Mas_ModifyBy] FOREIGN KEY([ModifyBy])REFERENCES [dbo].[Employee] ([EmployeeId])
    
)
