
	CREATE TABLE [dbo].[PlanBom]
(
	[PBomId] [int] IDENTITY(1,1) NOT NULL primary key,
    [Job_ord_no] [varchar](20) NOT NULL,
	[itemid] [int] NOT NULL,
	[sizeid] [int] NOT NULL,
	[colorid] [int] NULL,
	[access_type] [varchar](3) NOT NULL,
	[prg_qty] [numeric](14, 3) NULL,
	[request_qty] [numeric](14, 3) NULL,
	[head_office] [bit] NULL,
	[company_unitid] [int] NULL,
	[order_qty] [numeric](14, 3) NULL,
	[Received_Qty] [numeric](14, 3) NULL DEFAULT (0),
	[companyid] [int] NULL,
	[uc_order_qty] [numeric](14, 3) NULL,
	[storesissue] [numeric](14, 3) NULL,
	[prog_thru] [varchar](1) NULL,
	[BOM_qty] [numeric](14, 3) NULL,
	[Pur_UOMid] [int] NULL,
	[ToPurUOM] [numeric](14, 3) NULL DEFAULT (1),
	[Conv_Mode] [varchar](1) NULL DEFAULT ('M'),
	[base_bom_qty] [numeric](14, 3) NULL,
	[Adjust_Qty] [numeric](14, 3) NULL DEFAULT (0.00),
	[Debit_qty] [numeric](14, 3) NULL DEFAULT (0),
	[Transfer_In] [numeric](14, 3) NOT NULL DEFAULT (0.00),
	[Transfer_Out] [numeric](14, 3) NOT NULL DEFAULT (0.00),
	[Cancel_Qty] [numeric](14, 3) NULL,
	[OrderType] [varchar](1) NULL,
	[CSP] [varchar](1) NOT NULL DEFAULT ('N'),
	[Semi_Finished_Item] [varchar](2) NULL,
	[Issue] [bit] NULL,
	[ItemClosure] [char](1) NOT NULL DEFAULT ('N'),
	[ReturnQty] [numeric](14, 3) NULL DEFAULT (0),
	[StockIn] [numeric](14, 3) NULL DEFAULT (0),
	[StockOut] [numeric](14, 3) NOT NULL DEFAULT (0), 
    CONSTRAINT [FK_PlanBom_Company] FOREIGN KEY ([companyid]) REFERENCES [Company]([companyid]),
	 CONSTRAINT [FK_PlanBom_Uom] FOREIGN KEY ([Pur_UOMid]) REFERENCES [Unit_Of_Measurement]([UomId])
)

