CREATE TABLE [dbo].[Prod_Prg_Mas_Amend]
(
	[AmdProdPrgid] [int] IDENTITY(1,1) NOT NULL,
	[ProdPrgNo] [varchar](20) NULL,
	[ProgDate] [datetime] NULL,
	[ProcessId] [int] NULL,
	[Job_ord_no] [varchar](20) NULL,
	[processvarper] [int] NULL,
	[companyunitid] [int] NULL,
	[companyid] [int] NULL,
	[Startdate] [datetime] NULL,
	[Enddate] [datetime] NULL,
	[remarks] [varchar](1500) NULL DEFAULT (''),
	[OrderType] [varchar](1) NOT NULL,
	[ProgramType] [varchar](1) NULL,
	[Prog_Seq_No] [int] NULL,
	[Transfer] [char](1) NULL,
	[Closed] [varchar](1) NULL DEFAULT ('N') ,
	[IsProportion] [char](1) NULL,
	[Prop_Variance] [numeric](5, 2) NULL,
	[Amend] [varchar](1) NOT NULL DEFAULT ('N') ,
	[Approved] [char](1) NOT NULL DEFAULT ('N') ,
	[FinalizeAutoPost] [varchar](1) NOT NULL DEFAULT ('N'),
	[PlanRemarks] [varchar](50) NULL DEFAULT (null),
	[CreatedBy] [int] NULL,
	[ApprovedBy] [int] NULL,

	CONSTRAINT [PK_Prod_prg_masAmd] PRIMARY KEY (AmdProdPrgid),
	CONSTRAINT [FK_ApprovedByRefAmd] FOREIGN KEY (ApprovedBy) REFERENCES [Employee]([EmployeeId]),
	CONSTRAINT [FK_App_CompanyUnitRefAmd] FOREIGN KEY (companyunitid) REFERENCES CompanyUnit([Id]),
	CONSTRAINT [FK_App_CompanyRefAmd] FOREIGN KEY (companyid) REFERENCES Company([CompanyId]),
	CONSTRAINT [FK_CreatedRefAmd] FOREIGN KEY (CreatedBy) REFERENCES [Employee]([EmployeeId]),
	CONSTRAINT [FK_ProcessRefAmd] FOREIGN KEY (ProcessId) REFERENCES Process([ProcessId]), 
    CONSTRAINT [CK_Prod_Prg_MasAmd_OrderType] CHECK (([OrderType] = 'J' or [OrderType] = 'W' or [OrderType] = 'S')),
    CONSTRAINT [CK_Prod_Prg_MasAmd_FinalizeAutoPost] CHECK (([FinalizeAutoPost] = 'Y' or [FinalizeAutoPost] = 'N'))
)
