CREATE TABLE [dbo].[Prod_Prg_Det_Amend]
(
	[AmdProdprgdetid] [int] IDENTITY(1,1) NOT NULL,
    [AmdProdPrgid] [int] NULL,
	[Itemid] [int] NULL,
	[Colorid] [int] NULL,
	[Sizeid] [int] NULL,
	[ActualPlan_Qty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[Prog_Op_Qty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[order_qty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[InorOut] [varchar](1) NULL,
	[CatType] [varchar](100) NULL,
	[LastProcessid] [int] NULL,
	[BalanceQty] [numeric](14, 3) NULL DEFAULT (0),
	[Issue_qty] [numeric](12, 3) NULL DEFAULT (0),
	[Receipt_Qty] [numeric](12, 3) NULL DEFAULT (0),
	[Return_Qty] [numeric](12, 3) NULL DEFAULT (0),
	[Damage_qty] [numeric](12, 3) NULL DEFAULT (0),
	[Cancel_Qty] [numeric](9, 3) NULL DEFAULT (0),
	[Tolerance] [numeric](5, 3) NULL DEFAULT (0),
	[Returnable_Qty] [numeric](14, 3) NULL DEFAULT (0),
	[Closure_qty] [numeric](14, 3) NULL DEFAULT (0),
	[Excess_Qty] [numeric](12, 3) NOT NULL DEFAULT (0),
	[Inp_CancelQty] [numeric](14, 3) NULL DEFAULT (0),
	[transferIn] [numeric](12, 3) NULL DEFAULT (0),
	[transferOut] [numeric](12, 3) NULL DEFAULT (0),
	[IP_MarkupRate] [numeric](15, 5) NULL DEFAULT (0),
	[MarkupValue] [numeric](15, 5) NULL DEFAULT (0),
	[AltItem] [char](1) NOT NULL DEFAULT ('N'),
	[Dely_Qty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[SecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[OrderSecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[IssSecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[RecptSecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[Amended] [char](1) NULL DEFAULT ('N'),
	[Dely_Returnqty] [numeric](14, 3) NULL DEFAULT (0),
	[Loss_Qty] [numeric](14, 3) NULL DEFAULT (0.000),
	[buy_ord_ship] [varchar](8) NULL DEFAULT ('O'), 
    CONSTRAINT [PK_Prod_Prg_DetAmend] PRIMARY KEY ([AmdProdprgdetid]),
    CONSTRAINT [FK_ProdprgidAmend] FOREIGN KEY (AmdProdPrgid) REFERENCES [Prod_Prg_Mas_Amend]([AmdProdPrgid]),
    CONSTRAINT [FK_Prod_Prg_Det_ItemAmend] FOREIGN KEY ([Itemid]) REFERENCES [Item]([ItemId]),
	CONSTRAINT [FK_Prod_Prg_Det_ColorAmend] FOREIGN KEY ([Colorid]) REFERENCES [Color]([ColorId]),
	CONSTRAINT [FK_Prod_Prg_Det_SizeAmend] FOREIGN KEY ([Sizeid]) REFERENCES [Size]([SizeId]), 
    CONSTRAINT [CK_Prod_Prg_Det_IssueQtyAmend] CHECK (([Issue_Qty] >= 0)),
	CONSTRAINT [CK_Prod_Prg_Det_Order_QtyAmend] CHECK (([Order_Qty] >= 0)), 
    CONSTRAINT [CK_Prod_Prg_Det_AltItem1Amend] CHECK (([AltItem] = 'N' or [AltItem] = 'Y')),
	CONSTRAINT [CK_Prod_Prg_Det_Amended1Amend] CHECK (([Amended] = 'Y' or [Amended] = 'N')),
	CONSTRAINT [CK_Prod_Prg_Det_InorOut1Amend] CHECK (([InorOut] = 'O' or [InorOut] = 'I')),
)
