CREATE TABLE [dbo].[AccIssueMas]
(
	[IssueId] INT IDENTITY(1,1) NOT NULL,
	[IssueNo] [varchar](12) NOT NULL,
	[IssueDate] [datetime] NULL,
	[CompanyId] [int] NOT NULL,
	[CompanyunitID] [int] NOT NULL,
	[JobNo] [varchar](12) NOT NULL,
	[ProcessID] [int] NOT NULL,
	[Job_Work_sample] [varchar](1) NOT NULL,
	[ProgramNo] [varchar](12) NOT NULL,
	[Remarks] [varchar](500) NULL,
	[IssueType] [varchar](1) NULL,
	[WorkDivID] [int] NULL,
	[GatePassVehicle] [varchar](15) NOT NULL DEFAULT (''),
	[InternalOrExternal] [char](1) NOT NULL DEFAULT ('I'),
	[FromStoreid] [int] NULL,
	[Closed] [char](1) NULL,
	[CreatedBy] [int] NULL,
	[Issueunitid] [int] NULL,
	[CGST] [numeric](18, 3) NULL,
	[SGST] [numeric](18, 3) NULL,
	[IGST] [numeric](18, 3) NULL,
	[TotCGST] [numeric](18, 3) NULL,
	[TotSGST] [numeric](18, 3) NULL,
	[TotIGST] [numeric](18, 3) NULL,
	[Saccode] [varchar](50) NULL,
	CONSTRAINT [PK_AccIssueMasid] PRIMARY KEY ([IssueId]),
	CONSTRAINT [FK_accissuemasCompId] FOREIGN KEY ([CompanyId]) REFERENCES Company([CompanyId]),
	CONSTRAINT [FK_accissuemasProcessId] FOREIGN KEY (ProcessID) REFERENCES Process([ProcessId]),
	CONSTRAINT [FK_accissuemasCompUnitId] FOREIGN KEY (CompanyunitID) REFERENCES CompanyUnit([Id]),
	CONSTRAINT [FK_accissuemascreatedId] FOREIGN KEY (CreatedBy) REFERENCES [Employee]([EmployeeId]),
	CONSTRAINT [Fk_AccIssueMas_FromStoreid] FOREIGN KEY (FromStoreid) REFERENCES StoreUnit(StoreunitId),
)
