CREATE TABLE [dbo].[Component_Itemstock]
(
	[Stockid] INT IDENTITY(1,1) NOT NULL,
	[joborderno] [varchar](20) NULL,
	[Itemcat] [char](1) NULL,
	[Companyid] [int] NULL,
	[Unitid] [int] NULL,
	[Supplierid] [int] NULL,
	[Work_or_other] [char](1) NULL,
	[Processid] [int] NULL,
	[Transno] [varchar](20) NOT NULL,
	[TransDate] [datetime] NULL,
	[TransType] [char](3) NULL,
	[Itemid] [int] NULL,
	[ColorId] [int] NULL,
	[Sizeid] [int] NULL,
	[Componentid] [int] NULL,
	[LotNo] [varchar](10) NULL Default(''),
	[Qty] [numeric](12, 0) NOT NULL Default('0'),
	[Alloted] [numeric](12, 0) NOT NULL Default('0'),
	[BalQty]  AS ([Qty] - [Alloted]),
	[Rate] [numeric](12, 2) NOT NULL Default('0'),
	[Markup_Rate] [numeric](12, 2) NOT NULL Default('0'),
	[BundleNo] [varchar](12) NOT NULL Default(''),
	[Stocktype] [varchar](1) NULL Default('S'),
	[StockDate] [datetime] NULL,
	[StoreUnitid] [int] NULL,
	[Buy_Ord_ship] [varchar](8) NULL,
	[CColorID] [int] NULL,
	CONSTRAINT [PK_ComponentItemStckid] PRIMARY KEY ([Stockid]),
	CONSTRAINT [FK_ComponentItemstckColorId] FOREIGN KEY ([ColorId]) REFERENCES [color]([Colorid]),
	--CONSTRAINT [FK_ComponentItemstckbuyordshipId] FOREIGN KEY ([Buy_Ord_ship]) REFERENCES buy_ord_ship([buy_ord_ship]),
	CONSTRAINT [FK_ComponentItemstckCompanyId] FOREIGN KEY ([Companyid]) REFERENCES [Company]([CompanyId]),
	CONSTRAINT [FK_ComponentItemstckComponentId] FOREIGN KEY ([Componentid]) REFERENCES [component]([Componentid]),
	CONSTRAINT [FK_ComponentItemstckItemId] FOREIGN KEY ([Itemid]) REFERENCES Item(ItemId),
	CONSTRAINT [FK_ComponentItemstckProcessId] FOREIGN KEY ([Processid]) REFERENCES [Process]([Processid]),
	CONSTRAINT [FK_ComponentItemstckSizeId] FOREIGN KEY ([Sizeid]) REFERENCES Size(SizeId),
	CONSTRAINT [FK_ComponentItemstckColorRefId] FOREIGN KEY ([CColorID]) REFERENCES Color(ColorId),
	CONSTRAINT [FK_ComponentItemstckStoreunitId] FOREIGN KEY ([StoreUnitid]) REFERENCES StoreUnit([StoreUnitID]),
	CONSTRAINT [Ck_Component_Alloted] CHECK  ([Alloted] > 0),

)
