CREATE TABLE [dbo].[Cutting_Recpt_Det]
(
	[CuttingRecptDetID] INT IDENTITY(1,1) NOT NULL,
	[CuttingRecptId] [int] NULL,
	[Itemid] [int] NULL,
	[ColorID] [int] NULL,
	[Sizeid] [int] NULL,
	[Lotno] [varchar](10) NULL,
	[RecptQty] [numeric](12, 0) NOT NULL Default('0'),
	[SecQty] [numeric](12, 0) NOT NULL Default('0'),
	[Rate] [numeric](12, 2) NOT NULL Default('0'),
	[NoOfBundles] [numeric](5, 0) NOT NULL Default('0'),
	[IPMarkup_rate] [numeric](12, 2) NOT NULL Default('0'),
	[OPMarkup_rate] [numeric](12, 2) NOT NULL Default('0'),
	[Grammage] [numeric](14, 3) NOT NULL Default('0'),
	[weight] [numeric](14, 3) NOT NULL Default('0'),
	[InvQty] [numeric](12, 3) NOT NULL Default('0'),
	[Closed] [char](1) NOT NULL Default('N'),
	[Wages_Qty] [numeric](14, 3) NULL,
	[rejectedQty] [numeric](18, 0) NULL,
	[CuttingOrdDetId] INT NOT NULL,
	CONSTRAINT [PK_CuttinRecptdetid] PRIMARY KEY ([CuttingRecptDetID]),
	CONSTRAINT [FK_cuttingrefmasid] FOREIGN KEY ([CuttingRecptId]) REFERENCES [Cutting_Recpt_Mas]([CuttingRecptId]),
	CONSTRAINT [FK_colorrefid] FOREIGN KEY ([ColorID]) REFERENCES [Color]([Colorid]),
	CONSTRAINT [FK_itemrefid] FOREIGN KEY ([Itemid]) REFERENCES [Item]([ItemId]),
	CONSTRAINT [FK_Sizerefid] FOREIGN KEY ([Sizeid]) REFERENCES [Size]([SizeId]),
)
