CREATE TABLE [dbo].[Production_Ord_Mas]
(
	[productionordid] [int] IDENTITY(1,1) NOT NULL primary key,
	[productionorder] [varchar](20) NULL,
	[processordate] [datetime] NULL,
	[processorid] [int] NULL,
	[processid] [int] NULL,
	[remarks] [varchar](1500) NULL,
	[companyunitid] [int] NULL,
	[companyid] [int] NOT NULL,
	[ProcessorType] [varchar](2) NULL CHECK  (([ProcessorType] = 'P' or [ProcessorType] = 'W')),
	[OrderType] [varchar](2) NULL CHECK  (([OrderType] = 'W' or [OrderType] = 'J' or [OrderType] = 'S' or [OrderType] = 'G' or [OrderType] = 'L')),
	[Closed] [varchar](1) NULL DEFAULT ('N'),
	[OrderCumIssue] [varchar](15) NULL,
	[DelidateTime] [datetime] NULL,
	[ComboIds] [varchar](200) NOT NULL DEFAULT (''),
	[DispLocType] [varchar](1) NOT NULL CHECK  (([DispLocType] = 'P' or [DispLocType] = 'O' or [DispLocType] = 'S' or [DispLocType] = 'C')) DEFAULT ('S'),
	[DispLoc] [int] NOT NULL,
	[IssueLocType] [varchar](1) NOT NULL CHECK  (([IssueLocType] = 'O' or [IssueLocType] = 'C')) DEFAULT ('O'),
	[IssueLoc] [int] NOT NULL,
	[Teamid] [int] NULL,
	[StoreUnitId] [int] NULL,
	[CreatedBy] [int] NULL,
	[Phoneno] [varchar](100) NULL,
	[contactperson] [varchar](100) NULL,
	[amount] [numeric](12, 2) NULL,
	[taxamount] [numeric](12, 2) NULL,
	[saccode] [varchar](50) NULL,
	[CGST] [numeric](18, 3) NULL,
	[SGST] [numeric](18, 3) NULL,
	[IGST] [numeric](18, 3) NULL,
	[TotCGST] [numeric](18, 3) NULL,
	[TotSGST] [numeric](18, 3) NULL,
	[TotIGST] [numeric](18, 3) NULL,
	ModuleType varchar(1) null,
	CONSTRAINT [FK_Process_ord_mas_Companyid] FOREIGN KEY([companyid]) REFERENCES [dbo].[Company] ([CompanyId]),
	CONSTRAINT [FK_Process_ord_mas_Companyunitid] FOREIGN KEY([companyunitid]) REFERENCES [dbo].[CompanyUnit] ([Id]),
	CONSTRAINT [FK_Process_ord_mas_CreatedBy] FOREIGN KEY([CreatedBy]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [FK_Process_ord_mas_ProcessId] FOREIGN KEY([processid]) REFERENCES [dbo].[Process] ([ProcessId]),
	CONSTRAINT [Fk_ProcOrdMas_StoreId] FOREIGN KEY([StoreUnitId]) REFERENCES [dbo].[StoreUnit] ([StoreUnitID]),

)
