CREATE TABLE [dbo].[Prod_Recpt_Mas]
(
	[RecptId] INT IDENTITY(1,1) NOT NULL,
	[RecptNo] [varchar](20) NOT NULL,
	[RecptDate] [datetime] NULL,
	[CompanyId] [int] NOT NULL,
	[CompanyUnitID] [int] NOT NULL,
	[LineID] [int] NULL,
	[Job_Work_sample] [varchar](1) NOT NULL,
	[Remarks] [varchar](500) NOT NULL,
	[ProcessID] [int] NULL,
	[RecptType] [varchar](1) NULL,
	[WorkDivID] [int] NULL,
	[InternalOrExternal] [char](1) NOT NULL DEFAULT('I'),
	[DcNumber] [varchar](20) NOT NULL,
	[IssueID] [int] NULL,
	[Tostoreid] [int] NULL,
	[Buy_Ord_Ship] [varchar](8) NULL,
	[CreatedBy] [int] NULL,
	[FLineID] [int] NULL,
	[PrintTaken] [int] NULL,
	[Recpt_Ref_Date] [datetime] NULL,
	[UserId] [int] NULL,
	[JobNo] [varchar](20) NULL,
	[ProgramNo] [varchar](20) NULL,

	CONSTRAINT [PK_ProdRecptid] PRIMARY KEY ([RecptId]),
	--CONSTRAINT [FK_ProdrecptbuyordshipRefid] FOREIGN KEY ([Buy_Ord_Ship]) REFERENCES [buy_ord_ship]([buy_ord_ship]),
	CONSTRAINT [FK_ProdrecptIssueIdRefid] FOREIGN KEY (IssueID) REFERENCES [Prod_iss_mas]([ProdIssueid]),
	CONSTRAINT [FK_ProdrecptUserIdRefid] FOREIGN KEY (UserId) REFERENCES Username([userid]),
	CONSTRAINT [FK_ProdrecptemployeeIdRefid] FOREIGN KEY ([CreatedBy]) REFERENCES [employee]([employeeid]),
	CONSTRAINT [FK_ProdrecptstoreunitIdRefid] FOREIGN KEY ([Tostoreid]) REFERENCES [StoreUnit]([StoreUnitID]),
	CONSTRAINT [FK_ProdrecptcompanyIdRefid] FOREIGN KEY ([CompanyId]) REFERENCES [company]([companyid]),
	--CONSTRAINT [FK_ProdrecptcompanyIdRefid] FOREIGN KEY (FLineID) REFERENCES [Fixed_line_mas](FLineID),
	--CONSTRAINT [FK_ProdrecptcompanyIdRefid] FOREIGN KEY (LineID) REFERENCES [LineAllocationDet]([LDetid]),
	CONSTRAINT [FK_ProdrecptprocessIdRefid] FOREIGN KEY (ProcessID) REFERENCES Process(Processid),
	CONSTRAINT [FK_ProdrecptcompanyunitIdRefid] FOREIGN KEY ([CompanyUnitID]) REFERENCES Companyunit(id),
	CONSTRAINT [FK_ProdrecptnocheckconstraintRefid] CHECK  (([RecptNo] <> ''))
)
