CREATE TABLE [dbo].[Prod_Recpt_Det]
(
	[RecptDetID] INT IDENTITY(1,1) NOT NULL,
	[RecptId] int NOT NULL,
	[ItemId] [int] NOT NULL,
	[ColorId] [int] NOT NULL,
	[SizeID] [int] NOT NULL,
	[Uomid] [int] NOT NULL,
	[Rate] [numeric](15, 5) NULL,
	[ReceivedQty] [numeric](12, 3) NOT NULL,
	[RejectedQty] [numeric](12, 3) NOT NULL DEFAULT(0),
	[ExcessQty] [numeric](12, 3) NOT NULL DEFAULT(0),
	[RejectStkId] [int] NULL,
	[ExcessStkID] [int] NULL,
	[Bundled] [varchar](1) NULL,
	[Input_Rate] [numeric](12, 3) NOT NULL DEFAULT(0),
	[Process_rate] [numeric](12, 3) NOT NULL DEFAULT(0),
	[CatType] [varchar](3) NOT NULL,
	[GuomId] [int] NULL,
	[Wages_Qty] [numeric](14, 3) NULL,
	[JobNo] [varchar](20) NULL,
	[ProgramNo] [varchar](20) NULL,
	[IssueId] [int] NULL,

	CONSTRAINT [PK_ProdRecptDetid] PRIMARY KEY ([RecptDetID]),
	CONSTRAINT [FK_ProdrecptMasRefid] FOREIGN KEY ([RecptId]) REFERENCES [Prod_Recpt_Mas]([RecptId]),
	CONSTRAINT [FK_ProdrecptdetguomRefid] FOREIGN KEY ([GuomId]) REFERENCES [Garment_UOM]([GUOMid]),
	CONSTRAINT [FK_ProdrecptdetIssueIdRefid] FOREIGN KEY ([IssueId]) REFERENCES [Prod_iss_mas]([ProdIssueid]),
	CONSTRAINT [FK_ProdrecptdetcolorRefid] FOREIGN KEY ([ColorId]) REFERENCES [color]([colorid]),
	CONSTRAINT [FK_ProdrecptdetitemRefid] FOREIGN KEY ([ItemId]) REFERENCES [Item]([itemid]),
	CONSTRAINT [FK_ProdrecptdetsizeRefid] FOREIGN KEY ([SizeID]) REFERENCES [size]([sizeid]),
	CONSTRAINT [FK_ProdrecptdetuomRefid] FOREIGN KEY ([Uomid]) REFERENCES [Unit_of_measurement]([uomid]),
)
