CREATE TABLE [dbo].[ProductionInvoiceMas]
(
    [ProdInvid] [int] IDENTITY(1,1) NOT NULL,
	[OrderType] [varchar](1) NOT NULL,
	[InvNo] [varchar](20) NOT NULL,
	[InvDate] [datetime] NULL,
	[InvAmount] [numeric](12, 2) NOT NULL DEFAULT (0),
	[RefNo] [varchar](15) NOT NULL,
	[RefDate] [datetime] NULL,
	[Remarks] [varchar](150) NOT NULL DEFAULT (''),
	[PaymentAmt] [numeric](12, 2) NOT NULL DEFAULT (0),
	[Paid] [char](1) NULL DEFAULT ('N'),
	[Passed] [char](1) NULL DEFAULT ('N'),
	[Processorid] [int] NULL,
	[Processid] [int] NULL,
	[Companyid] [int] NULL,
	[InvoiceType] [char](1) NOT NULL,
	[InternalOrExternal] [char](1) NOT NULL DEFAULT ('I'),
	[CompanyUnitId] [int] NULL,
	[Approved] [char](1) NOT NULL DEFAULT ('N'),
	[voucherid] [int] NULL,
	[ledgerid] [int] NULL,
	[CreatedBy] [int] NULL,
	[ApprovedBy] [int] NULL,
	[Saccode] [varchar](50) NULL,
	[CGST] [numeric](18, 3) NULL,
	[SGST] [numeric](18, 3) NULL,
	[IGST] [numeric](18, 3) NULL,
	[TotCGST] [numeric](18, 3) NULL,
	[TotSGST] [numeric](18, 3) NULL,
	[TotIGST] [numeric](18, 3) NULL,
	[EWayNo] [varchar](25) NULL,
	[EWayDate] [datetime] NULL, 
    CONSTRAINT [PK_ProductionInvoiceMas] PRIMARY KEY ([ProdInvid]), 
    CONSTRAINT [FK_ProductionInvoiceMas_company] FOREIGN KEY ([Companyid]) REFERENCES [company]([Companyid]),
	CONSTRAINT [FK_ProductionInvoiceMas_company_unit] FOREIGN KEY ([CompanyUnitId]) REFERENCES [companyunit]([id]),
	CONSTRAINT [FK_ProductionInvoiceMas_process] FOREIGN KEY ([processid]) REFERENCES [process]([processid]),
	CONSTRAINT [FK_ProductionInvoiceMas_employee] FOREIGN KEY ([CreatedBy]) REFERENCES [employee]([employeeid]),
	CONSTRAINT [FK_ProductionInvoiceMas_ApprovedBy] FOREIGN KEY ([ApprovedBy]) REFERENCES [employee]([employeeid]),
	CONSTRAINT [FK_ProductionInvoiceMas_voucher] FOREIGN KEY ([voucherid]) REFERENCES [voucher]([voucherid]),
	CONSTRAINT [FK_ProductionInvoiceMas_ledger] FOREIGN KEY ([ledgerid]) REFERENCES [ledger]([ledgerid]), 
    CONSTRAINT [CK_ProductionInvoiceMas_InternalOrExternal] CHECK (([InternalOrExternal] = 'I' or [InternalOrExternal] = 'E')),
	CONSTRAINT [CK_ProductionInvoiceMas_InvoiceType] CHECK (([InvoiceType] = 'C' or [InvoiceType] = 'G' or [InvoiceType] = 'M' or [InvoiceType] = 'S')),
	CONSTRAINT [CK_ProductionInvoiceMas_OrderType] CHECK (([OrderType] = 'J' or [OrderType] = 'W' or [OrderType] = 'S'))
)
