CREATE TABLE [dbo].[Buy_Ord_Mas]
(  
	[Buy_Ord_MasId] [int] IDENTITY(1,1) NOT NULL,
	[Order_No] [varchar](20) NOT NULL,
	[Order_Date] [datetime] NULL,
	[BuyerId] [int] NULL,
	[Buyer_AddId] [int] NULL,
	[ManagerId] [int] NULL,
	[MerchandiserId] [int] NULL,
	[Ref_No] [varchar](45) NULL,
	[Ref_Date] [datetime] NULL,
	[Pay_SystemId] [int] NULL,
	[SystemId] [int] NULL,
	[Payment_ModeId] [int] NULL,
	[AgentId] [int] NULL,
	[Agent_AddId] [int] NULL,
	[ShipAgentId] [int] NULL,
	[ShipAgent_AddId] [int] NULL,
	[CurrencyId] [int] NULL,
	[Exchange] [numeric](15, 5) NULL,
	[Cancel] [bit] NOT NULL DEFAULT ('0'),
	[Comit] [bit] NOT NULL DEFAULT ('0'),
	[CompanyId] [int] NULL,
	[Closed] [char](1) NULL DEFAULT ('N'),
	[CloseDate] [datetime] NULL,
	[Quantity] [int] NULL,
	[Cost_def] [varchar](1) NULL DEFAULT ('N'),
	[GuomId] [int] NULL,
	[Guom_Conv] [smallint] NULL,
	[Agency_Per] [numeric](5, 2) NULL,
	[Bas_Unit] [int] NULL,
	[Remarks] [varchar](1000) NULL,
	[ClaimType] [varchar](1) NOT NULL DEFAULT ('R'),
	[NominatedForwarder] [varchar](1) NOT NULL DEFAULT ('N'),
	[CSP] [varchar](1) NOT NULL DEFAULT ('N'),
	[Buyer_Ref_No] [varchar](45) NULL,
	[TransAmend] [char](1) NOT NULL DEFAULT ('N') ,
	[ConsigneeId] [int] NULL,
	[CreatedBy] [int] NULL,
	[OrdType] [char](1) NULL,
	[Consignee_AddId] [int] NULL, 
	ParentOrderId int null,
	[EnquiryId] [int] NULL,
	QuoteId int null,
	ModifyBy int null,
	[Modify_Date] [datetime] NULL,
	[PA] [char](1) NULL DEFAULT ('P'),
	RevQuoteId int null,
	RevQuoteNo [varchar](25) NULL,
	[Rev] [char](1) NULL,
	[OrdPost] [char](1) NULL,
	[PlanPost] [char](1) NULL,
	[FOrderNo] [varchar](1) NULL,
    CONSTRAINT [FK_buy_ord_mas_buyer] FOREIGN KEY ([BuyerId]) REFERENCES [Buyer]([BuyerId]),
	CONSTRAINT [FK_buy_ord_mas_company] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([CompanyId]),
	CONSTRAINT [FK__buy_ord_m__Manag] FOREIGN KEY([ManagerId]) REFERENCES [dbo].[employee] ([employeeId]),	
    CONSTRAINT [FK__buy_ord_m__Merch] FOREIGN KEY([MerchandiserId])REFERENCES [dbo].[employee] ([employeeId]),
	--CONSTRAINT [Fk_buy_ord_mas_Buyer_CurrencyId] FOREIGN KEY([CurrencyId])REFERENCES [dbo].[currency] ([currencyId]),
	CONSTRAINT [Fk_buy_ord_mas_Buyer_mode_of_shipmentId] FOREIGN KEY([Payment_ModeId])REFERENCES [dbo].[Mode_Of_Shipment] ([Mode_of_ShipmentId]),
	CONSTRAINT [Fk_buy_ord_mas_Buyer_Pay_SystemId] FOREIGN KEY([Pay_SystemId])REFERENCES [dbo].[payment_terms] ([pay_termId]),
	CONSTRAINT [Fk_buy_ord_mas_Buyer_SystemId] FOREIGN KEY([SystemId])REFERENCES [dbo].[ShipmentSystem] ([SystemId]),
	CONSTRAINT [FK_Buy_Ord_Mas_CreatedBy] FOREIGN KEY([CreatedBy])REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [FK_Buy_Ord_Mas_ModifyBy] FOREIGN KEY([ModifyBy])REFERENCES [dbo].[Employee] ([EmployeeId]),
	--CONSTRAINT [FK_Buy_Ord_Mas_Consignee] FOREIGN KEY([Consignee_AddId])REFERENCES [dbo].[Consignee_Add] ([Consignee_AddId]),
    CONSTRAINT [FK_Buy_Ord_Mas_GarmentUom] FOREIGN KEY([Bas_Unit])REFERENCES [dbo].[Garment_Uom] ([GUomId]),
	CONSTRAINT [FK_Buy_Ord_Mas_Buyer_Add] FOREIGN KEY([Buyer_AddId])REFERENCES [dbo].[Buyer] ([BuyerId]),
	CONSTRAINT [FK_Buy_Ord_Mas_Agent_Add] FOREIGN KEY([Agent_AddId])REFERENCES [dbo].[Agent] ([AgentId]),
	CONSTRAINT [FK_Buy_Ord_Mas_Agent] FOREIGN KEY([AgentId])REFERENCES [dbo].[Agent] ([AgentId]), 
    CONSTRAINT [FK_Buy_Ord_Mas_GUom] FOREIGN KEY([GuomId])REFERENCES [dbo].[Garment_Uom] ([GUomId]), 
    CONSTRAINT [PK_Buy_Ord_Mas] PRIMARY KEY ([Buy_Ord_MasId])
	--CONSTRAINT [FK_Buy_Ord_Mas_Ship] FOREIGN KEY([ShipAgentId])REFERENCES [dbo].[Agent] ([AgentId]),
	--CONSTRAINT [FK_Buy_Ord_Mas_ShipAdd] FOREIGN KEY([ShipAgent_AddId])REFERENCES [dbo].[Agent] ([AgentId])
	
)
