CREATE TABLE [dbo].[Buy_Ord_Det]
(
	[Buy_Ord_DetId] [int] IDENTITY(1,1) NOT NULL,
	[Buy_Ord_Ship] [varchar](8) NOT NULL,
	[ColorId] [int] NOT NULL,
	[SizeId] [int] NOT NULL,
	[Quantity] [numeric](8, 0) NULL,
	[Job_Qty] [numeric](8, 0) NULL DEFAULT ('0'),
	[Finish_Qty] [numeric](8, 0) NULL DEFAULT ('0'),
	[StyleRowId] [int] NULL,
	[ShipRow] [int] NULL,
	[ColorRow] [int] NULL,
	[SizeRow] [int] NULL,
	[Buy_Ord_MasId] [int] NULL,
	[Order_No] [varchar](20) NULL,
	[Despatch_Qty] [numeric](12, 0) NOT NULL DEFAULT ('0'),
	[Rate] [numeric](15, 5) NULL,
	[AllowanceQty] [numeric](9, 0) NULL,
	[ProductionQty] [numeric](9, 0) NULL,
	[RateUpdated] [bit] NULL,
	[ITEMID] [int] NULL,
	[ItemRow] [int] NULL,
	[OrderColorId] [int] NULL,
	[ProdAmend] [varchar](1) NOT NULL DEFAULT ('N'),
	[Packed_Qty] [int] NULL,
	[ComboColorId] [int] NULL,
	CONSTRAINT [PK_Buy_Ord_Det] PRIMARY KEY ([Buy_Ord_DetId]), 
    CONSTRAINT [FK_Buy_Ord_Det_OrdColor] FOREIGN KEY ([OrderColorId]) REFERENCES [Color]([Colorid]),
	CONSTRAINT [FK_Buy_Ord_Det_ComboColor] FOREIGN KEY ([ComboColorId]) REFERENCES [Color]([Colorid]),
	CONSTRAINT [FK_Buy_Ord_Det_Color] FOREIGN KEY ([ColorId]) REFERENCES [Color]([Colorid]),
	CONSTRAINT [FK_Buy_Ord_Det_Item] FOREIGN KEY (ITEMID) REFERENCES [Item]([ItemId]),
	CONSTRAINT [FK_Buy_Ord_Det_Size] FOREIGN KEY ([SizeId]) REFERENCES [Size]([SizeId]),
	CONSTRAINT [FK_Buy_Ord_Det_buy_ord_mas] FOREIGN KEY ([Buy_Ord_MasId]) REFERENCES [Buy_Ord_Mas]([Buy_Ord_MasId]),
	CONSTRAINT [FK_Buy_Ord_Det_Buy_Ord_Style] FOREIGN KEY ([StyleRowId]) REFERENCES [buy_ord_style]([StyleRowid])
)
