CREATE TABLE [dbo].[Communication]
(
	[Id] [int] IDENTITY(1,1) NOT NULL, 
    [Companyid] INT NOT NULL, 
    [Buyerid] INT NULL, 
    [Supplierid] INT NULL, 
    [Agentid] INT NULL, 
    [Others] NVARCHAR(50) NULL, 
    [EntryNo] NVARCHAR(100) NULL, 
    [EntryDate] DATETIME NULL, 
    [RefNo] NVARCHAR(50) NULL, 
    [RefDate] DATETIME NULL, 
    [EnquiryNo] NVARCHAR(50) NULL, 
    [OrderNo] NVARCHAR(50) NULL, 
    [OrderRefNo] NVARCHAR(50) NULL, 
    [MiscRefNo] NVARCHAR(50) NULL, 
    [CompanyType] CHAR NULL, 
    [From] DATETIME NULL, 
    [To] DATETIME NULL, 
    [CompanyModeid] INT NULL, 
    [Subject] NVARCHAR(100) NULL, 
    [Description] NVARCHAR(100) NULL, 
    [Inward] CHAR NULL, 
    [Remarks] NVARCHAR(100) NULL, 
    CONSTRAINT [PK_Communication] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_CommCompany] FOREIGN KEY ([Companyid]) REFERENCES [Company]([CompanyId]),
	--CONSTRAINT [FK_CommBuyer] FOREIGN KEY ([Buyerid]) REFERENCES [Buyer]([BuyerId]),
	--CONSTRAINT [FK_CommSupplier] FOREIGN KEY ([Supplierid]) REFERENCES [Supplier]([SupplierId]),
	--CONSTRAINT [FK_CommAgent] FOREIGN KEY ([Agentid]) REFERENCES [Agent]([AgentId]),
)
