CREATE TABLE [dbo].[Job_Ord_Mas]
(
	
	ID int IDENTITY(1,1) NOT NULL,
	[Job_Ord_No] [varchar](20) NOT NULL UNIQUE,
	[Job_Ord_Date] [datetime] NULL,
	[Quotation_No] [varchar](20) NULL,
	[Order_No] [varchar](20) NULL,
	[Sales_sample] [varchar](1) NULL,
	[Styleid] [int] NULL,
	[Supplierid] [int] NULL,
	[Unit_or_other] [varchar](1) NULL CHECK  (([Unit_or_other] = 'S' or [Unit_or_other] = 'P')),
	[Merch_id] [int] NULL,
	[Qc_id] [int] NULL,
	[Job_Order_Ref] [varchar](20) NULL,
	[Programmed] [bit] NULL,
	[FlatProgrammed] [bit] NULL,
	[Quantity] [numeric](8, 0) NULL,
	[Finish_qty] [numeric](8, 0) NULL,
	[Despatch_qty] [numeric](8, 0) NULL,
	[Exchange] [numeric](15, 5) NULL,
	[Buyerid] [int] NULL,
	[Comit] [bit] NULL,
	[Cancel] [bit] NULL,
	[ExcessPer] [numeric](5, 2) NULL,
	[Companyid] [int] NULL,
	[Despatch_closed] [bit] NOT NULL DEFAULT (0),
	[Stylerowid] [int] NULL,
	[Amend] [varchar](1) NOT NULL DEFAULT ('N'),
	[JobOrWork] [varchar](1) NOT NULL CHECK  (([JobOrWork] = 'J' or [JobOrWork] = 'S' or [JobOrWork] = 'D' or [JobOrWork] = 'W')),
	[WorkOrd_Qty] [numeric](8, 0) NULL,
	[Rate] [numeric](15, 5) NULL,
	[LocationId] [int] NULL,
	[Issue_Date] [datetime] NULL,
	[StageId] [int] NULL,
	[Remarks] [varchar](500) NULL DEFAULT (''),
	[RateType] [varchar](2) NOT NULL DEFAULT ('PR'),
	[ToApprove] [int] DEFAULT (null),
	[ApprovedBy] [int] NULL,
	[ApprovedDate] [datetime] NULL,
	[IsApproved] [varchar](1) NULL DEFAULT ('N'),
	[CurrencyID] [int] NULL,
	[Consumption] [varchar](50) NULL,
	[Rate_Desc] [varchar](50) NULL,
	[JobOrdType] [varchar](1) NULL DEFAULT ('I'),
	[ProcessUnitID] [int] NULL,
	[CreatedBy] [int] NULL,
	[FIN_JobNo] [varchar](20) NULL,
	[FINYEAR] [varchar](10) NULL,
	[ModifyBy] [int] null,
	[Modify_Date] [datetime] NULL,
	CONSTRAINT [FK_ToBuyer] FOREIGN KEY ([Buyerid]) REFERENCES [Buyer]([BuyerId]),
	CONSTRAINT [FK_ToCompany] FOREIGN KEY ([Companyid]) REFERENCES [Company]([CompanyId]),
	CONSTRAINT [FK_ToCurrency] FOREIGN KEY ([CurrencyID]) REFERENCES [Currency]([CurrencyId]),
	CONSTRAINT [FK_ProcessUnitID] FOREIGN KEY([ProcessUnitID])REFERENCES [CompanyUnit] ([Id]),
	CONSTRAINT [fk_qc_id] FOREIGN KEY([Qc_id]) REFERENCES [Employee] ([EmployeeId]),
	CONSTRAINT [fk_approved] FOREIGN KEY([ApprovedBy]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [fk_Job_Ord_mas_stylerowid] FOREIGN KEY([Stylerowid])REFERENCES [dbo].[buy_ord_style] ([StyleRowid]),
	CONSTRAINT [fk1_jom_style] FOREIGN KEY([Styleid])REFERENCES [dbo].[styleheader] ([styleId]),
	CONSTRAINT [PK_JobOrdMas] PRIMARY KEY ([ID]),
	CONSTRAINT [FK_Job_Ord_mas_ModifyBy] FOREIGN KEY([ModifyBy])REFERENCES [dbo].[Employee] ([EmployeeId])

)


