CREATE TABLE [dbo].[MarkQuoteMas_Amend]
(
	[RecId] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[QuoteID] [int] NOT NULL,
	[QuoteNo] [varchar](20) NOT NULL,
	[QuoteDate] [datetime] NULL,
	[QuoteType] [varchar](1) NOT NULL,
	[Companyid] [int] NOT NULL,
	[BuyerId] [int] NOT NULL,
	[EnquiryId] [int] NULL,
	[StyleId] [int] NOT NULL,
	[CategoryId] [int] NULL,
	[YarnAdd] [numeric](5, 2) NULL,
	[ProcessAdd] [numeric](5, 2) NULL,
	[AccAdd] [numeric](5, 2) NULL,
	[CMTadd] [numeric](5, 2) NULL,
	[CommercialAdd] [numeric](5, 2) NULL,
	[FabricCost] [numeric](15, 5) NULL,
	[AccessoryCost] [numeric](15, 5) NULL,
	[CMTcost] [numeric](15, 5) NULL,
	[Commercial] [numeric](15, 5) NULL,
	[TotalCost] [numeric](15, 5) NULL,
	[ProfitPercent] [numeric](5, 2) NULL,
	[CurrencyID] [int] NOT NULL,
	[ExchangeRate] [numeric](15, 5) NULL,
	[Remarks] [varchar](500) NULL,
	[QuotedRate] [numeric](15, 5) NULL  DEFAULT (0),
	[TemplateName] [varchar](40) NULL DEFAULT (null),
	[CreatedBy] [int] NULL,
	[OrderQty] NUMERIC(15,2) NULL,
	[RefNo] [varchar](50) NULL,
	[ProcessWastagePer] NUMERIC(12,2) NULL,
	[BuyerPrice] NUMERIC(12,2) NULL,
	PA char(1) NULL,
	 CONSTRAINT [fk_MarkQuoteMas_AmendBuyerid] FOREIGN KEY([BuyerId]) REFERENCES [dbo].[Buyer] ([BuyerId]),
	 CONSTRAINT [fk_MarkQuoteMas_AmendCategoryid] FOREIGN KEY([CategoryId]) REFERENCES [dbo].[Category] ([CategoryId]),
	 CONSTRAINT [fk_MarkQuoteMas_AmendCompanyid] FOREIGN KEY([Companyid]) REFERENCES [dbo].[Company] ([CompanyId]),
	 CONSTRAINT [FK_MarkQuoteMas_AmendCreatedBy] FOREIGN KEY([CreatedBy]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	  CONSTRAINT [fk_MarkQuoteMas_AmendCurrencyid] FOREIGN KEY([CurrencyID]) REFERENCES [dbo].[Currency] ([CurrencyId]),
	  --CONSTRAINT [fk_MarkQuoteMas_AmendEnquiryId] FOREIGN KEY([EnquiryId]) REFERENCES [dbo].[MarkEnqMas] ([EnquiryId]),
	  --CONSTRAINT [fk_MarkQuoteMas_AmendStyleId] FOREIGN KEY([EnquiryId]) REFERENCES [dbo].[MarkEnqMas] ([EnquiryId]),
)
