CREATE TABLE [dbo].[TestingDCMas]
(
	[TestingDCId] INT IDENTITY(1,1) NOT NULL primary key,
	DCNo varchar(20) NOT NULL,
	[DCDate] [datetime] NULL,
	CompanyId int NULL,
	SupplierId int NULL,
	ColorId int NULL,
	TestOn int NULL,
	TestValue decimal(18,3) NULL,
	BuyerId int NULL,
	OrderId int NULL,
	VehicleNo varchar(20) NULL,
	GatePassNo int NULL,
	DebitOnSuppId int NULL,
	DebitOnUnitId int NULL,
	TaxId int NULL,
	HSNCODE varchar(50) NULL,
	Remarks varchar(100) NULL,
	[CreatedBy] [int] NULL,
	ModifyBy int null,
	[Modify_Date] [datetime] NULL,
	[IsActive] [bit] NOT NULL DEFAULT (1) ,
	CancelNarr varchar(100) NULL,
	CONSTRAINT [fk_TestingDC_Buyerid] FOREIGN KEY(BuyerId) REFERENCES [dbo].[Buyer] ([BuyerId]),
	CONSTRAINT [fk_TestingDC_Supplierid] FOREIGN KEY(SupplierId) REFERENCES [dbo].Supplier (SupplierId),
	CONSTRAINT [fk_TestingDC_Taxid] FOREIGN KEY(TaxId) REFERENCES [dbo].AddLess (AddlessId),
	CONSTRAINT [fk_TestingDC_OrderId] FOREIGN KEY(OrderId) REFERENCES [dbo].Buy_Ord_Mas (Buy_Ord_MasId),
)
