CREATE TABLE [dbo].[TestingDCReceiptMas]
(
	[TestingDCReceiptId] INT IDENTITY(1,1) NOT NULL primary key,
	DCReceiptNo varchar(20) NOT NULL,
	[DCReceiptDate] [datetime] NULL,
	TestingDCId int NOT NULL,
	SupplierId int NULL,
	CompanyId int NULL,
	OrderId int NULL,
	OrderRefNo varchar(200) NULL,
	BillNo varchar(20) NULL,
	BillDate datetime NULL,
	Remarks varchar(200) NULL,
	GSTtaxId int NULL,
	TestValue decimal(18,3) NULL,
	CGST_Per decimal(18,2) NULL Default('0'),
	CGSTValue decimal(18,2) NULL Default('0'),
	SGST_Per decimal(18,2) NULL Default('0'),
	SGSTValue decimal(18,2) NULL Default('0'),
	IGST_Per decimal(18,2) NULL Default('0'),
	IGSTValue decimal(18,2) NULL Default('0'),
	TotalValue decimal(18,2) NULL,
	PA char(1) NULL Default('P'),
	CreatedBy int NULL,
	ModifyBy int NULL,
	ModifyDate datetime NULL,
	CONSTRAINT [fk_TestingDCReceipt_Supplierid] FOREIGN KEY(SupplierId) REFERENCES [dbo].Supplier (SupplierId),
	CONSTRAINT [fk_TestingDCReceipt_TestingDCID] FOREIGN KEY(TestingDCId) REFERENCES [dbo].[TestingDCMas] ([TestingDCId]),
	CONSTRAINT [fk_TestingDCReceipt_OrderId] FOREIGN KEY(OrderId) REFERENCES [dbo].Buy_Ord_Mas (Buy_Ord_MasId),
	CONSTRAINT [fk_TestingDCReceipt_Taxid] FOREIGN KEY(GSTtaxId) REFERENCES [dbo].AddLess (AddlessId),
)
