CREATE TABLE [dbo].[Indent_Det]
(
	[Indentdetid] [int] IDENTITY(1,1) NOT NULL,
	[Indentmasid] [int] NULL,
	[Itemid] [int] NULL,
	[Colorid] [int] NULL,
	[Sizeid] [int] NULL,
	[UOMid] [int] NULL,
	[Quantity] [numeric](14, 3) NULL DEFAULT (0),
	[PurOrderQty] [numeric](14, 3) NULL DEFAULT (0),
	[ReceivedQty] [numeric](14, 3) NULL DEFAULT (0),
	[Reqdate] [datetime] NULL,
	[ItemRemark] [varchar](500) NULL DEFAULT (''),
	[Sec_Qty] [numeric](14, 3) NULL DEFAULT (0),
	[Sec_UOMid] [int] NULL,
	[Mfrid] [int] NULL,
	[Cancel_Qty] [numeric](14, 3) NULL DEFAULT (0),
	[Close_Qty] [numeric](14, 3) NULL DEFAULT (0),
	[RefConversion] [numeric](14, 3) NULL DEFAULT (0),
	[AppQty] [numeric](14, 3) NULL,
	[Item_Purpose] [varchar](500) NULL DEFAULT (Null),
	[MachineID] [int] NULL DEFAULT (Null),
	[AppRejRemarks] [varchar](2500) NULL DEFAULT (Null),
	[BalanceQty] [numeric](14, 3) NULL DEFAULT (0),
	[ActualAppQty] [numeric](14, 3) NULL DEFAULT (0),
	[Quoteid] [int] NULL DEFAULT (Null),
	[Quotedate] [datetime] NULL,
	[Rate] [numeric](14, 3) NULL DEFAULT (0),
	[AppRate] [numeric](14, 9) NULL,
	[PurcancelQty] [numeric](14, 3) NULL DEFAULT (0), 
    CONSTRAINT [PK_Indent_Det] PRIMARY KEY ([Indentdetid]), 
    CONSTRAINT [FK_Indent_Det_color] FOREIGN KEY ([Colorid]) REFERENCES [color]([Colorid]),
	CONSTRAINT [FK_Indent_Det_Item] FOREIGN KEY ([Itemid]) REFERENCES [Item]([Itemid]),
	CONSTRAINT [FK_Indent_Det_Size] FOREIGN KEY ([Sizeid]) REFERENCES [Size]([Sizeid]),
	CONSTRAINT [FK_Indent_Det_Unit_of_measurement] FOREIGN KEY ([Uomid]) REFERENCES [Unit_of_measurement]([Uomid]),
    CONSTRAINT [FK_Indent_Det_SecUnit_of_measurement] FOREIGN KEY ([Sec_UOMid]) REFERENCES [Unit_of_measurement]([Uomid]),
	CONSTRAINT [FK_Indent_Det_Supplier] FOREIGN KEY ([Mfrid]) REFERENCES [Supplier]([Supplierid])
)
