CREATE TABLE [dbo].[Indent_Mas]
(
	[IndentMasid] INT IDENTITY(1,1) NOT NULL, 
	[IndentNo] [varchar](20) NULL,
	[Companyid] [int] NULL,
	[Company_unitid] [int] NULL,
	[IndentDate] [datetime] NULL,
	[Purchase_Type] [varchar](2) NULL,
	[Purchase_itemType] [varchar](3) NULL,
	[Remarks] [varchar](1000) NULL DEFAULT (''),
	[LocalImport] [varchar](1) NULL,
	[Closed] [varchar](1) NULL,
	[Cancel] [varchar](1) NULL,
	[Approved] [char](1) NULL DEFAULT (''),
	[EmployeeId] [int] NULL,
	[Departmentid] [int] NULL,
	[SectionID] [int] NULL,
	[Exchange_Rate] [numeric](14, 3) NULL,
	[IndentHead] [varchar](100) NULL DEFAULT (''),
	[CurrencyId] [int] NULL,
	[CapitalOrRevenue] [varchar](1) NULL DEFAULT('R'),
	[IndentType] [char](1) NULL,
    CONSTRAINT [PK_Indent_Mas] PRIMARY KEY ([IndentMasid]), 
    CONSTRAINT [FK_Indent_Mas_Company_Unit] FOREIGN KEY ([Company_unitid]) REFERENCES [companyunit]([Id]), 	
	CONSTRAINT [FK_Indent_Mas_Company] FOREIGN KEY ([Companyid]) REFERENCES [Company]([CompanyId]), 	
	CONSTRAINT [FK_Indent_Mas_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [Currency]([CurrencyId]), 	
	CONSTRAINT [FK_Indent_Mas_Department] FOREIGN KEY ([Departmentid]) REFERENCES [Department]([Id]), 
	CONSTRAINT [FK_Indent_Mas_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [Employee]([EmployeeId]), 
    CONSTRAINT [CK_Indent_Mas_CapitalOrRevenue] CHECK (([capitalOrRevenue] = 'R' or [CapitalOrRevenue] = 'C'))
)
