CREATE TABLE [dbo].[JJForm]
(
	[JJMasID] [int] IDENTITY(1,1) NOT NULL primary key,
	[AsstYear] [varchar](50) NOT NULL,
	[EntryNo] [varchar](50) NOT NULL,
	[EntryDate] [datetime] NULL,
	[CompanyID] [int] NULL,
	[CompanyUnitID] [int] NULL,
	[SupplierType] [char](1) NULL CHECK  (([supplierType] = 'U' or [supplierType] = 'S')),
	[SupplierID] [int] NULL,
	[FromGoods] [varchar](500) NULL,
	[ToGoods] [varchar](500) NULL,
	[ItemGroupID] [int] NULL,
	[ItemRemarks] [varchar](500) NULL,
	[Quantity] [numeric](14, 3) NULL,
	[UOMID] [int] NULL,
	[Amount] [numeric](14, 3) NULL,
	[TransportPurpose] [char](5) NOT NULL,
	[VehicleNo] [varchar](250) NULL,
	[AuthorizerID] [int] NULL,
	[Remarks] [varchar](500) NULL,
	[CreatedBy] [int] NULL,
	[Identification_Marks] [varchar](250) NULL,
	[Process_Duration] [int] NULL,
	[DC_Number] [varchar](50) NULL,
	[DC_Type] [varchar](50) NULL,
	[Cancel] [bit] NULL,
	[Rate] [numeric](14, 3) NULL,

	CONSTRAINT [FK_JJForm_Authorizer] FOREIGN KEY([AuthorizerID]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [FK_JJform_CompanyID] FOREIGN KEY([CompanyID]) REFERENCES [dbo].[Company] ([CompanyId]),
	CONSTRAINT [FK_JJForm_CompUnitId] FOREIGN KEY([CompanyUnitID]) REFERENCES [dbo].[CompanyUnit] ([Id]),
	CONSTRAINT [FK_JJForm_CreatedBy] FOREIGN KEY([CreatedBy]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [FK_JJForm_ItemGroupID] FOREIGN KEY([ItemGroupID]) REFERENCES [dbo].[ItemGroup] ([Id]),
	CONSTRAINT [FK_JJForm_UOMID] FOREIGN KEY([UOMID]) REFERENCES [dbo].[Unit_of_measurement] ([UomId]),
)
