CREATE TABLE [dbo].[Lot_Creation_Det]
(
	[LotDetId] INT IDENTITY(1,1) NOT NULL, 
	[LotID] [int] NULL,
	[Order_No] [varchar](25) NULL,
	[StyleId] [int] NULL,
	[ItemId] [int] NULL,
	[ColorId] [int] NULL,
	[SizeId] [int] NULL,
	[ProgramQty] [numeric](14, 3) NULL DEFAULT (0),
	[AllowancePer] [numeric](14, 3) NULL DEFAULT (0),
	[OrderQty] [numeric](14, 3) NULL DEFAULT (0),
	[IssuedQty] [numeric](14, 3) NULL DEFAULT (0),
	[ReceiptQty] [numeric](14, 3) NULL DEFAULT (0),
	[CancelQty] [numeric](14, 3) NULL DEFAULT (0),
	[ReturnQty] [numeric](14, 3) NULL DEFAULT (0),
	[LossQty] [numeric](14, 3) NULL DEFAULT (0),
	[KnittingColorid] [int] NULL,
	[GSM] [int] NULL,
    CONSTRAINT [PK_Lot_Creation_Det] PRIMARY KEY ([LotDetId]), 
    CONSTRAINT [FK_Lot_Creation_Det_Item] FOREIGN KEY ([ItemId]) REFERENCES [Item]([itemId]), 
	CONSTRAINT [FK_Lot_Creation_Det_color] FOREIGN KEY ([ColorId]) REFERENCES [Color]([ColorId]), 
	CONSTRAINT [FK_Lot_Creation_Det_size] FOREIGN KEY ([SizeId]) REFERENCES [Size]([SizeId]), 
	CONSTRAINT [FK_Lot_Creation_Det_LotMas] FOREIGN KEY ([LotID]) REFERENCES [Lot_Creation_Mas]([LotId]), 
	CONSTRAINT [FK_Lot_Creation_Det_Knitsize] FOREIGN KEY ([KnittingColorid]) REFERENCES [Size]([SizeId]), 
)
