CREATE TABLE [dbo].[OpenDebitMas]
(
	[DebitId] [int] IDENTITY(1,1) NOT NULL,
	[DebitNo] [varchar](20) NULL,
	[DebitDate] [datetime] NULL,
	[Companyid] [int] NOT NULL,
	[Partyid] [int] NOT NULL,
	[RefNo] [varchar](75) NULL,
	[RefDate] [datetime] NULL,
	[Processid] [int] NULL,
	[Amount] [numeric](12, 3) NULL,
	[Remarks] [varchar](1000) NULL,
	[voucherid] [int] NULL,
	[ledgerid] [int] NULL,
	[OpenOrOrder] [char](1) NULL,
	[OrderType] [varchar](1) NULL,
	[Order_No] [varchar](20) NULL,
	[Styleid] [int] NULL,
	[DebitOrCredit] [varchar](1) NOT NULL DEFAULT ('D'),
	[CreatedBy] [int] NULL,
	[VehicleNo] [varchar](25) NULL,
	[Addless_amount] [numeric](18, 3) NULL,
	[AddLessManualOrFormula] [varchar](1) NULL,
	[CurrencyID] [int] NULL,
	[ExchangeRate] [numeric](18, 3) NULL, 
    CONSTRAINT [PK_OpenDebitMas] PRIMARY KEY ([DebitId]), 
    CONSTRAINT [FK_OpenDebitMas_Ledger] FOREIGN KEY ([ledgerid]) REFERENCES [Ledger]([LedgerId]),
	CONSTRAINT [FK_OpenDebitMas_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [Voucher]([VoucherId]),
	CONSTRAINT [FK_OpenDebitMas_StyleHeader] FOREIGN KEY ([Styleid]) REFERENCES [StyleHeader]([Styleid]),
	CONSTRAINT [FK_OpenDebitMas_Employee] FOREIGN KEY ([CreatedBy]) REFERENCES [Employee]([Employeeid]), 
    CONSTRAINT [CK_OpenDebitMas_DebitOrCredit] CHECK (([DebitOrCredit] = 'D' or [DebitOrCredit] = 'C')),
	CONSTRAINT [CK_OpenDebitMas_OpenOrOrder] CHECK (([OpenOrOrder] = 'O' or [OpenOrOrder] = 'P')),
	CONSTRAINT [CK_OpenDebitMas_OrderType] CHECK (([OrderType] = 'B' or [OrderType] = 'S')),
)
