CREATE TABLE [dbo].[Pur_Grn_Det]
(	
	[Grn_DetId] [int] IDENTITY(1,1) NOT NULL,
    [Grn_MasId] [int] NOT NULL,
	[itemid] [int] NULL,
	[sizeid] [int] NULL,
	[colorid] [int] NULL,
	[received_qty] [numeric](13, 3) NOT NULL DEFAULT (0.00),
	[uomId] [int] NULL,
	[rate] [numeric](12, 2) NULL,
	[balance] [numeric](13, 3) NOT NULL DEFAULT (0.00),
	[invoiced_qty] [numeric](13, 3) NOT NULL DEFAULT (0.00),
	[debit_id] [int] NULL,
	[excess_qty] [numeric](13, 3) NULL DEFAULT (0.00),
	[debit_rate] [numeric](7, 2) NULL,
	[MfrId] [int] NULL,
	[Sec_Qty] [numeric](12, 3) NULL,
	[Excess_Stockid] [int] NULL,
	[rejected_qty] [numeric](12, 3) NULL DEFAULT (0),
	[shortage_qty] [numeric](12, 3) NULL DEFAULT (0),
	[accepted_qty] [numeric](12, 3) NULL DEFAULT (0),
	[return_qty] [numeric](12, 3) NULL DEFAULT (0),
	[debit_qty] [numeric](12, 3) NULL DEFAULT (0),
	[receivable_qty] [numeric](12, 3) NULL DEFAULT (0),
	[Qlty_Excess] [numeric](12, 3) NULL DEFAULT (0),
	[Excess_return] [numeric](12, 3) NULL DEFAULT (0),
	[itemremarks] [varchar](250) NULL,
	[Closed] [bit] NOT NULL DEFAULT (0),
	[Short_stkid] [int] NULL DEFAULT (0),
	[Reject_stkid] [int] NULL DEFAULT (0),
	[QltyItemRemarks] [varchar](500) NULL,
	[ReturnQty] [numeric](14, 3) NULL,
	[Grn_RtnId] [int] NULL,
	[Excessrate] [numeric](12, 2) NULL,
    CONSTRAINT [PK_Pur_Grn_Det] PRIMARY KEY ([grn_detid]), 
    CONSTRAINT [FK_Pur_Grn_Det_GrnMas] FOREIGN KEY ([Grn_MasId]) REFERENCES [Pur_Grn_Mas]([Grn_MasId]), 
	CONSTRAINT [FK_Pur_Grn_Det_Item] FOREIGN KEY ([itemid]) REFERENCES [item]([itemid]), 
	 CONSTRAINT [FK_Pur_Grn_Det_Color] FOREIGN KEY ([colorid]) REFERENCES [color]([colorId]), 
	  CONSTRAINT [FK_Pur_Grn_Det_Size] FOREIGN KEY ([sizeid]) REFERENCES [size]([sizeId]), 
	  CONSTRAINT [FK_Pur_Grn_Det_Uom] FOREIGN KEY ([uomId]) REFERENCES [unit_of_measurement]([uomId]), 
	   CONSTRAINT [FK_Pur_Grn_Det_Employee] FOREIGN KEY ([MfrId]) REFERENCES [Employee]([Employeeid])
)
