CREATE TABLE [dbo].[Pur_Ord_Det]
(
	[Pur_Ord_DetId] INT IDENTITY(1,1) NOT NULL, 
	[Pur_ord_id] [int] NOT NULL,
	[ItemID] [int] NULL,
	[SizeID] [int] NULL,
	[ColorID] [int] NULL,
	[UOMId] [int] NULL,
	[quantity] [numeric](15, 3) NOT NULL DEFAULT (0),
	[ReceivedQty] [numeric](15, 3) NOT NULL DEFAULT (0.00),
	[Rate] [numeric](15, 5) NOT NULL DEFAULT (0.00),
	[Reqdate] [datetime] NULL,
	[ItemRemark] [varchar](200) NULL,
	[Sec_Qty] [numeric](15, 3) NOT NULL DEFAULT (0),
	[Sec_UOMid] [int] NULL,
	[Mfrid] [smallint] NULL,
	[Cancel_Qty] [numeric](15, 3) NOT NULL DEFAULT (0.00),
	[Close_Qty] [numeric](15, 3) NOT NULL DEFAULT (0.00),
	[Amend] [varchar](1) NULL DEFAULT ('N'),
	[currencyid] [int] NULL,
	[exchangerate] [numeric](15, 5) NOT NULL DEFAULT (0),
	[receivable_qty] [numeric](15, 3) NOT NULL DEFAULT (0),
	[Debit_qty] [numeric](15, 3) NOT NULL DEFAULT (0),
	[RefConversion] [numeric](8, 3) NULL,
	[ReturnQty] [numeric](14, 3) NULL,
	[reqdatefrom] [varchar](50) NULL,
	[reqdatto] [varchar](50) NULL,
	[reqdateto] [varchar](50) NULL,
	[CGSTAMt] [numeric](18, 3) NULL,
	[SGSTAMT] [numeric](18, 3) NULL,
	[IGSTAMT] [numeric](18, 3) NULL,
	[CGST] [numeric](18, 3) NULL,
	[SGST] [numeric](18, 3) NULL,
	[IGST] [numeric](18, 3) NULL,
	[HSNCODE] [varchar](50) NULL,
	[TOTCGSTAMT] [numeric](18, 3) NULL,
	[TOTSGSTAMT] [numeric](18, 3) NULL,
	[TOTIGSTAMT] [numeric](18, 3) NULL,
	[IndDetId] [int] NULL, 
    CONSTRAINT [PK_Pur_Ord_Det] PRIMARY KEY ([Pur_Ord_DetId]), 
    CONSTRAINT [FK_Pur_Ord_Det_Color] FOREIGN KEY ([ColorID]) REFERENCES [Color]([ColorId]), 	
	 CONSTRAINT [FK_Pur_Ord_Det_Size] FOREIGN KEY ([SizeID]) REFERENCES [Size]([SizeId]), 
	  CONSTRAINT [FK_Pur_Ord_Det_Item] FOREIGN KEY ([ItemID]) REFERENCES [Item]([ItemId]), 
	   CONSTRAINT [FK_Pur_Ord_Det_Currency] FOREIGN KEY ([currencyid]) REFERENCES [Currency]([CurrencyId]), 
	     CONSTRAINT [FK_Pur_Ord_Det_PurOrdMas] FOREIGN KEY ([Pur_Ord_id]) REFERENCES [Pur_Ord_Mas]([Pur_ord_id]), 
		  CONSTRAINT [FK_Pur_Ord_Det_SecUom] FOREIGN KEY ([Sec_UOMid]) REFERENCES [Unit_of_measurement]([uomid]), 
		  	  CONSTRAINT [FK_Pur_Ord_Det_UomId] FOREIGN KEY ([UOMid]) REFERENCES [Unit_of_measurement]([uomid])
)
