CREATE TABLE [dbo].[Pur_Grn_Mas]
(
    [Grn_MasId] INT IDENTITY(1,1) NOT NULL, 
	[receipt_no] [varchar](20) NOT NULL,
	[receipt_date] [datetime] NULL,
	[companyid] [int] NULL,
	[company_unitid] [int] NULL,
	[supplierid] [int] NULL,
	[Dc_no] [varchar](50) NULL,
	[Dc_date] [datetime] NULL,
	[remarks] [varchar](1000) NULL,
	[grncommit] [bit] NOT NULL DEFAULT (0),
	[grncancel] [bit] NOT NULL DEFAULT (0),
	[grnclose] [bit] NULL DEFAULT (0),
	[pur_type] [varchar](2) NULL,
	[job_ord_no] [varchar](20) NULL,
	[Amend] [varchar](1) NULL DEFAULT ('N'),
	[Qlty_No] [varchar](20) NULL,
	[Qlty_date] [datetime] NULL,
	[QltyRemarks] [varchar](1000) NULL,
	[Inward_No] [varchar](20) NULL,
	[Pur_ItemType] [varchar](1) NOT NULL,
	[DebtRaised] [varchar](1) NOT NULL DEFAULT ('N'),
	[StoreUnitID] [int] NULL,
	[CreatedBy] [int] NULL,
	[Supp_Inv_No] [varchar](50) NULL,
	[QCReport_No] [varchar](50) NULL,
	[ExcludeInv] [bit] NULL DEFAULT (0),
	IsAccountsPosted bit null,
	[SuppInvDate] [datetime] NULL,
    CONSTRAINT [PK_Pur_grn_mas] PRIMARY KEY ([Grn_MasId]), 
    CONSTRAINT [FK_Pur_grn_mas_company] FOREIGN KEY ([companyid]) REFERENCES [Company]([CompanyId]), 	
    CONSTRAINT [FK_Pur_grn_mas_companyunit] FOREIGN KEY ([company_unitid]) REFERENCES [CompanyUnit]([Id]), 
	CONSTRAINT [FK_Pur_grn_mas_Supplier] FOREIGN KEY ([supplierid]) REFERENCES [Supplier]([SupplierId]), 
	CONSTRAINT [FK_Pur_grn_mas_Employee] FOREIGN KEY ([CreatedBy]) REFERENCES [Employee]([EmployeeId]), 
    CONSTRAINT [CK_Pur_grn_mas_Pur_ItemType] CHECK (([Pur_ItemType] = 'Y' or [Pur_ItemType] = 'A' or [Pur_ItemType] = '')), 
	CONSTRAINT [CK_Pur_grn_mas_pur_type] CHECK (([pur_type] = 'O' or [pur_type] = 'G' or [pur_type] = 'R' or [pur_type] = 'SP'))
)
