CREATE TABLE [dbo].[Pur_Inv_Mas]
(

    [pur_invid] [int] IDENTITY(1,1) NOT NULL,
	[invoice_no] [varchar](20) NOT NULL,
	[invoice_date] [datetime] NULL,
	[company_id] [int] NOT NULL,
	[company_unitid] [int] NULL,
	[supplierid] [int] NULL,
	[Gross_amount] [numeric](15, 5) NULL DEFAULT (0),
	[Addless_amount] [numeric](15, 5) NULL DEFAULT (0),
	[invoice_value] [numeric](15, 5) NULL DEFAULT (0),
	[supp_inv_no] [varchar](50) NULL,
	[supp_inv_date] [datetime] NULL,
	[remarks] [varchar](1000) NULL,	
	[ThroughDcInv] [varchar](20) NULL,
	[commitcancel] [varchar](1) NULL,
	[CreditID] [int] NULL,
	[DebitID] [int] NULL,
	[Payment_Amt] [numeric](15, 5) NULL DEFAULT (0),
	[Paid] [bit] NULL,
	[Passed] [bit] NULL,
	[DebtRaised] [varchar](1) NOT NULL DEFAULT ('N'),
	[Approved] [char](1) NOT NULL DEFAULT ('N'),
	[ledgerid] [int] NULL,
	[voucherid] [int] NULL,
	[AddLessManualOrFormula] [varchar](1) NOT NULL DEFAULT ('M'),
	[CurrencyId] [int] NULL,
	[ExchangeRate] [numeric](6, 2) NULL,
	[CreatedBy] [int] NULL,
	[ApprovedBy] [int] NULL,
	[EWayNo] [varchar](25) NULL,
	[EWayDate] [date] NULL, 
    CONSTRAINT [PK_Pur_Inv_Mas] PRIMARY KEY ([pur_invid]), 
	 CONSTRAINT [FK_Pur_Inv_Mas_Pur_Inv_Debit_Credit] FOREIGN KEY ([CreditID]) REFERENCES [Pur_Inv_Debit_Credit]([Debit_CreditID]),
	 CONSTRAINT [FK_Pur_Inv_Mas_Pur_Inv_Debit_Credit_Deb] FOREIGN KEY ([DebitID]) REFERENCES [Pur_Inv_Debit_Credit]([Debit_CreditID]),
    CONSTRAINT [FK_Pur_Inv_Mas_Company] FOREIGN KEY ([company_id]) REFERENCES [Company]([CompanyId]),
	CONSTRAINT [FK_Pur_Inv_Mas_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [Currency]([CurrencyId]),
	CONSTRAINT [FK_Pur_Inv_Mas_Supplier] FOREIGN KEY ([supplierid]) REFERENCES [Supplier]([SupplierId]),
	CONSTRAINT [FK_Pur_Inv_Mas_Ledger] FOREIGN KEY ([ledgerid]) REFERENCES [Ledger]([ledgerid]),
	CONSTRAINT [FK_Pur_Inv_Mas_voucher] FOREIGN KEY ([voucherid]) REFERENCES [voucher]([voucherid]),	 
    CONSTRAINT [CK_Pur_Inv_Mas_AddLessManualOrFormula] CHECK (([AddLessManualOrFormula] = 'F' or [AddLessManualOrFormula] = 'M'))
)
