CREATE TABLE [dbo].[Pur_Ord_Mas]
(
	[pur_ord_id] INT IDENTITY(1,1) NOT NULL, 	
	[pur_ord_no] [varchar](25) NOT NULL,
	[companyid] [int] NOT NULL,
	[company_unitid] [int] NULL,
	[orddate] [datetime] NULL,
	[supplierid] [int] NULL,
	[Purchase_Type] [varchar](2) NOT NULL,
	[Purchase_ItemType] [varchar](1) NOT NULL,
	[job_ord_no] [varchar](20) NULL,
	[remarks] [varchar](2000) NULL,
	[ord_commit] [varchar](1) NULL,
	[cancel] [bit] NOT NULL DEFAULT (0),
	[Unit_Supplier_Self] [varchar](1) NOT NULL,
	[Unit_Supplier] [int] NOT NULL,
	[Amount] [numeric](15, 5) NOT NULL DEFAULT (0),
	[ord_close] [bit] NULL,
	[Millid] [int] NULL,
	[styleid] [int] NULL,
	[unit_or_other] [varchar](1) NULL,
	[Amend] [varchar](1) NULL DEFAULT ('N'),
	[currencyid] [int] NULL,
	[exchange_rate] [numeric](15, 5) NOT NULL DEFAULT (0),
	[LocalImport] [varchar](1) NOT NULL DEFAULT ('L'),
	[Paytermid] [int] NULL,
	[ReqNo] [varchar](20) NULL,
	[ReqDate] [datetime] NULL,
	[BillCompany] [int] NULL,
	[BillCompType] [char](1) NULL,
	[TaxPercent] [numeric](15, 2) NOT NULL DEFAULT (0),
	[TaxAmount] [numeric](15, 5) NOT NULL DEFAULT (0),
	[WITH_ANNEXURE] [char](1) NOT NULL DEFAULT ('N'),
	[Closed] [varchar](1) NOT NULL DEFAULT ('N'),
	[remainderid] [int] NULL DEFAULT (null),
	[AddLessType] [char](1) NOT NULL DEFAULT ('G'),
	[AddLessManualOrFormula] [varchar](1) NULL DEFAULT ('M'),
	[IsApproved] [char](1) NULL DEFAULT (null),
	[ToApprove] [int] NULL DEFAULT (null),
	[ApprovedBY] [int] NULL DEFAULT (null),
	[ApproveDate] [datetime] NULL DEFAULT (null),
	[RateMode] [char](1) NULL DEFAULT ('0'),
	[CreatedBy] [int] NULL,
	[Potype] [varchar](2) NULL,
	[TOTCGSTAMT] [numeric](18, 3) NULL,
	[TOTSGSTAMT] [numeric](18, 3) NULL,
	[TOTIGSTAMT] [numeric](18, 3) NULL,
    [paymode] [varchar](10) NOT NULL,
	[chequeno] [varchar](30) NULL,
	[chequedate] [datetime] NULL,
	[advance] [numeric](15, 5) NOT NULL,	

    CONSTRAINT [PK_Pur_Ord_Mas] PRIMARY KEY ([Pur_Ord_Id]), 
    CONSTRAINT [FK_Pur_Ord_Mas_company] FOREIGN KEY ([companyid]) REFERENCES [Company]([CompanyId]), 
	CONSTRAINT [FK_Pur_Ord_Mas_companyunit] FOREIGN KEY ([company_unitid]) REFERENCES [companyunit]([Id]), 
    CONSTRAINT [FK_Pur_Ord_Mas_Supplier] FOREIGN KEY ([supplierid]) REFERENCES [supplier]([SupplierId]), 
	CONSTRAINT [FK_Pur_Ord_Mas_Employee] FOREIGN KEY ([ApprovedBY]) REFERENCES [Employee]([EmployeeId]), 
	CONSTRAINT [FK_Pur_Ord_Mas_EmployeeToApprove] FOREIGN KEY ([ToApprove]) REFERENCES [Employee]([EmployeeId]), 
	CONSTRAINT [FK_Pur_Ord_Mas_PayTerms] FOREIGN KEY ([Paytermid]) REFERENCES [Payment_Terms]([Pay_Termid]), 
	CONSTRAINT [FK_Pur_Ord_Mas_EmplCreate] FOREIGN KEY ([CreatedBy]) REFERENCES [Employee]([Employeeid]), 
	CONSTRAINT [FK_Pur_Ord_Mas_Currency] FOREIGN KEY ([currencyid]) REFERENCES [Currency]([Currencyid]), 
    CONSTRAINT [CK_Pur_Ord_Mas_AddLessManualOrFormula] CHECK (([AddLessManualOrFormula] = 'M' or [AddLessManualOrFormula] = 'F')), 
    CONSTRAINT [CK_Pur_Ord_Mas_AddLessType] CHECK (([AddLessType] = 'F' or [AddLessType] = 'G')), 
    CONSTRAINT [CK_Pur_Ord_Mas_billcompany] CHECK ([billcompany] <> 0), 
	CONSTRAINT [CK_Pur_Ord_Mas_BillCompType] CHECK (([BillCompType] = 'U' or [BillCompType] = 'B' or [BillCompType] = 'C' or [BillCompType] = 'S' or [BillCompType] = 'N')), 
	CONSTRAINT [CK_Pur_Ord_Mas_localimport] CHECK (([localimport] = 'L' or [localimport] = 'I')), 
	CONSTRAINT [CK_Pur_Ord_Mas_Purchase_ItemType] CHECK (([Purchase_ItemType] = 'Y' or [Purchase_ItemType] = 'A' or [Purchase_ItemType] = '')), 
    CONSTRAINT [CK_Pur_Ord_Mas_purchase_type] CHECK (([purchase_type] = 'S' or [purchase_type] = 'SP' or [purchase_type] = 'B' or [purchase_type] = 'R' or [purchase_type] = 'G' or [purchase_type] = 'P')), 
	CONSTRAINT [CK_Pur_Ord_Mas_RateMode] CHECK (([RateMode] = 'O' or [RateMode] = 'P')), 
	CONSTRAINT [CK_Pur_Ord_Mas_unit_supplier] CHECK (([unit_supplier] <> 0)), 
	CONSTRAINT [CK_Pur_Ord_Mas_Unit_Supplier_Self] CHECK (([Unit_Supplier_Self] = 'F' or [Unit_Supplier_Self] = 'U' or [Unit_Supplier_Self] = 'S' or [Unit_Supplier_Self] = 'T')), 
	CONSTRAINT [CK_Pur_Ord_Mas_with_annexure] CHECK (([with_annexure] = 'Y' or [with_annexure] = 'N')),
	CONSTRAINT [CK_Pur_Ord_Mas_PayMode] CHECK (([paymode]='DD' OR [paymode]='Cheque' OR [paymode]='Cash' OR [paymode]='LC' OR [paymode]='RTGS' OR [paymode]='NEFT'OR [paymode]='NILL'))
)
