CREATE TABLE [dbo].[Stores_Issue_Mas]
(
	[IssueId] INT IDENTITY(1,1) NOT NULL, 
	[Issueno] [varchar](20) NOT NULL,
	[Issuedate] [datetime] NULL,
	[Companyunitid] [int] NOT NULL,
	[Companyid] [int] NOT NULL,
	[Joborderno] [varchar](20) NULL,
	[Unit_supplier_self] [char](1) NOT NULL,
	[desunitid] [int] NULL,
	[remarks] [varchar](250) NULL,
	[Job_Mac_Gen] [varchar](2) NULL,
	[issue_Commit] [varchar](1) NOT NULL,
	[reqorstock] [varchar](1) NULL,
	[issueunit] [int] NOT NULL,
	[unit_or_other] [char](1) NOT NULL,
	[ItemType] [varchar](1) NOT NULL,
	[GatePassVehicle] [varchar](15) NULL,
	[QualityMade] [char](1) NOT NULL DEFAULT ('N'),
	[QltyRemarks] [varchar](250) NULL DEFAULT (''),
	[RequestnerId] [int] NULL,
	[FromStoreUnitID] [int] NULL,
	[CreatedBy] [int] NULL,
	[Deptid] [int] NULL,
	[SplNo] [int] NULL,
    CONSTRAINT [PK_Stores_Issue_Mas] PRIMARY KEY ([IssueId]), 
    CONSTRAINT [FK_Stores_Issue_Mas_Department] FOREIGN KEY ([Deptid]) REFERENCES [Department]([Id]), 
	CONSTRAINT [FK_Stores_Issue_Mas_StoreUnit] FOREIGN KEY ([FromStoreUnitID]) REFERENCES [StoreUnit]([StoreUnitID]), 
	CONSTRAINT [FK_Stores_Issue_Mas_Company] FOREIGN KEY ([Companyid]) REFERENCES [company]([Companyid]), 
	CONSTRAINT [FK_Stores_Issue_Mas_employee] FOREIGN KEY ([CreatedBy]) REFERENCES [Employee]([Employeeid]), 
    CONSTRAINT [CK_Stores_Issue_Mas_Issueno] CHECK (([issueno] <> '')), 
	CONSTRAINT [CK_Stores_Issue_Mas_Job_Mac_Gen] CHECK (([Job_Mac_Gen] = 'W' or [Job_Mac_Gen] = 'P' or [Job_Mac_Gen] = 'R' or [Job_Mac_Gen] = 'S' or [Job_Mac_Gen] = 'G' or [Job_Mac_Gen] = 'SP')), 
	CONSTRAINT [CK_Stores_Issue_Mas_ItemType] CHECK (([itemType] = 'Y' or [ItemType] = 'A' or [ItemType] = '')), 
	CONSTRAINT [CK_Stores_Issue_Mas_unit_or_other] CHECK (([unit_or_other] = 'P' or [unit_or_other] = 'S')),
	CONSTRAINT [CK_Stores_Issue_Mas_Unit_Supplier_Self] CHECK (([Unit_Supplier_Self] = 'F' or [Unit_Supplier_Self] = 'U' or [Unit_Supplier_Self] = 'T' or [Unit_Supplier_Self] = 'S')),

)
