CREATE TABLE [dbo].[Stores_Issue_Det]
(
	[IssueDetId] INT IDENTITY(1,1) NOT NULL, 
	[IssueId] [int] NOT NULL,
	[Itemid] [int] NULL,
	[Colorid] [int] NULL,
	[Sizeid] [int] NULL,
	[Quantity] [numeric](15, 3) NOT NULL,
	[returnqty] [numeric](14, 3) NULL,
	[uomid] [int] NULL,
	[Sec_Qty] [numeric](12, 3) NULL DEFAULT (0),
	[UnitStockid] [int] NULL,
	[ItemRemarks] [varchar](400) NULL,
	[qtyremarks] [varchar](100) NULL,
	[Sec_uomid] [int] NULL,
	[RefConversion] [numeric](8, 3) NULL DEFAULT (1),
	[Sec_qty1] [numeric](15, 3) NOT NULL,
	[Sec_uomid1] [int] NULL,
	[QltyItemRemarks] [varchar](500) NOT NULL DEFAULT (''),
	[ReceivedQty] [numeric](15, 3) NOT NULL DEFAULT (0),
	[RejectedQty] [numeric](12, 3) NOT NULL DEFAULT (0),
	[RejectStockId] [int] NULL,
	[ExcessQty] [numeric](9, 3) NULL, 
	[PlannedSizeID] [int] NULL,
    CONSTRAINT [FK_Stores_Issue_Det_Unit_of_measurement] FOREIGN KEY([uomid]) REFERENCES [dbo].[Unit_of_measurement] ([uomid]),
	CONSTRAINT [FK_Stores_Issue_Det_Color] FOREIGN KEY([Colorid])REFERENCES [dbo].[color] ([colorid]),
	CONSTRAINT [FK_Stores_Issue_Det_Stores_Issue_mas] FOREIGN KEY([IssueId]) REFERENCES [dbo].[Stores_Issue_mas] ([IssueId]),
	CONSTRAINT [FK_Stores_Issue_Det_Item] FOREIGN KEY([Itemid]) REFERENCES [dbo].[Item] ([itemid]),
	CONSTRAINT [FK_Stores_Issue_Det_size] FOREIGN KEY([Sizeid]) REFERENCES [dbo].[size] ([sizeid]),
	CONSTRAINT [FK_Stores_Issue_Det_Unit_of_measuremenSec] FOREIGN KEY([Sec_uomid]) REFERENCES [dbo].[Unit_of_measurement] ([uomid]), 
    CONSTRAINT [PK_Stores_Issue_Det] PRIMARY KEY ([IssueDetId])
)
