//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerCharges
    {
        public int BuyerchargesId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<decimal> FromQuantity { get; set; }
        public Nullable<decimal> ToQuantity { get; set; }
        public Nullable<decimal> ShippingExpense { get; set; }
        public Nullable<decimal> CIFExpense { get; set; }
        public Nullable<decimal> BankExpense { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
