//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerAmendDetails
    {
        public int amendID { get; set; }
        public Nullable<System.DateTime> amendDate { get; set; }
        public string Order_no { get; set; }
        public Nullable<int> Styleid { get; set; }
        public Nullable<decimal> AmendQty { get; set; }
    }
}
