//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyordapptitle
    {
        public int TitleId { get; set; }
        public string order_no { get; set; }
        public Nullable<int> styleid { get; set; }
        public Nullable<int> Approvalid { get; set; }
        public string ordertype { get; set; }
    
        public virtual OrderStyleHeader StyleHeader { get; set; }
    }
}
