//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorGroup
    {
        public ColorGroup()
        {
            this.Color = new HashSet<Color>();
        }
    
        public int ColorGroupID { get; set; }
        public string ColorGroup1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Color> Color { get; set; }
    }
}
