//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combosize
    {
        public int CombosizeId { get; set; }
        public Nullable<int> ComboSizeSeq { get; set; }
        public Nullable<int> StyleRowId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> Sizerow { get; set; }
    
        public virtual buy_ord_style buy_ord_style { get; set; }
        public virtual OrderSize Size { get; set; }
    }
}
