//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Defn_BOM
    {
        public int Cost_Defn_id { get; set; }
        public int Cost_Defn_BOMid { get; set; }
        public Nullable<int> Processid { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<int> Colorid { get; set; }
        public Nullable<int> Sizeid { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public decimal Rate { get; set; }
        public Nullable<int> UOMid { get; set; }
        public string Access_Type { get; set; }
        public decimal Actual_Qty { get; set; }
        public decimal Actual_Rate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public decimal ExRate { get; set; }
        public decimal CurrencyRate { get; set; }
        public decimal AppRate { get; set; }
        public decimal AppCurrencyRate { get; set; }
        public string DisplayOption { get; set; }
        public decimal AppQty { get; set; }
        public Nullable<System.DateTime> lUpdateDate { get; set; }
        public decimal FirstRate { get; set; }
        public string IsSecQty { get; set; }
        public decimal SecQty { get; set; }
        public decimal AppSecQty { get; set; }
        public decimal ActualSecQty { get; set; }
        public Nullable<decimal> Invoice_Qty { get; set; }
        public Nullable<decimal> Invoice_Rate { get; set; }
        public Nullable<decimal> Invoice_SecQty { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual PlanningColor Color { get; set; }
        public virtual PlanningItem Item { get; set; }
        public virtual PlanningUnit_of_measurement Unit_of_measurement { get; set; }
        public virtual Cost_Defn_Mas Cost_Defn_Mas { get; set; }
    }
}
