//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Company = new HashSet<Company>();
        }
    
        public int CurrencyId { get; set; }
        public string Currency1 { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<decimal> Exchangerate { get; set; }
        public Nullable<int> CountryID { get; set; }
        public bool Euro { get; set; }
        public byte Decimalplace { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Company> Company { get; set; }
    }
}
