//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cutting_Return_det
    {
        public int CuttingReturnDetId { get; set; }
        public Nullable<int> CuttingReturnId { get; set; }
        public Nullable<int> CuttingIssueDetId { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> sizeid { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> LossQty { get; set; }
        public Nullable<decimal> SecQty { get; set; }
        public Nullable<int> CuttingIssueStockid { get; set; }
        public string lotNo { get; set; }
    
        public virtual Cutting_Issue_Det Cutting_Issue_Det { get; set; }
        public virtual Cutting_Issue_Stock Cutting_Issue_Stock { get; set; }
        public virtual Cutting_Return_Mas Cutting_Return_Mas { get; set; }
    }
}
