//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cutting_Order_Det
    {
        public Cutting_Order_Det()
        {
            this.Cutting_Cancel_det = new HashSet<Cutting_Cancel_det>();
        }
    
        public int CuttingOrdDetid { get; set; }
        public Nullable<int> CuttingOrdId { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> sizeid { get; set; }
        public Nullable<int> PlannedSizeid { get; set; }
        public string inp_op { get; set; }
        public decimal Consumption { get; set; }
        public decimal Weight { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> Issuedqty { get; set; }
        public decimal rate { get; set; }
        public decimal receivedqty { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> LossQty { get; set; }
        public decimal Markup_Rate { get; set; }
        public decimal Markup_Value { get; set; }
        public decimal CancelQty { get; set; }
    
        public virtual ICollection<Cutting_Cancel_det> Cutting_Cancel_det { get; set; }
    }
}
