//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabric_Requisition_Det
    {
        public Nullable<int> Fabric_Req_Masid { get; set; }
        public int Fabric_Req_detid { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<int> Colorid { get; set; }
        public Nullable<int> Sizeid { get; set; }
        public Nullable<int> ComboColorid { get; set; }
        public Nullable<int> Uomid { get; set; }
        public string LotNo { get; set; }
        public string BatchNo { get; set; }
        public Nullable<decimal> AvailStock { get; set; }
        public Nullable<decimal> FabricWt { get; set; }
        public Nullable<decimal> ReqWt { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public string IsChecked { get; set; }
    
        public virtual PurchaseColor Color { get; set; }
        public virtual PurchaseColor Color1 { get; set; }
        public virtual Fabric_Requisition_Mas Fabric_Requisition_Mas { get; set; }
        public virtual PurchaseItem Item { get; set; }
        public virtual PurchaseSize Size { get; set; }
    }
}
