//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricProcess
    {
        public int FabricProcessmasid { get; set; }
        public Nullable<int> Fabricmasid { get; set; }
        public Nullable<int> Processid { get; set; }
        public Nullable<decimal> LossPercentage { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual FabricMaster FabricMaster { get; set; }
        public virtual MasterProcess Process { get; set; }
    }
}
