//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finyear
    {
        public int Finyear1 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string YearCode { get; set; }
        public string Period { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Reposted { get; set; }
        public string DBName { get; set; }
        public byte[] Created { get; set; }
        public Nullable<bool> SetDefault { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string FinType { get; set; }
    }
}
