//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Prod_Prg_Det
    {
        public int GrpProdPgmdetid { get; set; }
        public Nullable<int> GrpProdPrgid { get; set; }
        public Nullable<int> Prodprgid { get; set; }
        public Nullable<int> Processid { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<int> Colorid { get; set; }
        public Nullable<int> Sizeid { get; set; }
        public Nullable<decimal> Prog_Op_Qty { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public Nullable<decimal> GrpQty { get; set; }
        public string InorOut { get; set; }
        public Nullable<decimal> rate { get; set; }
    
        public virtual Group_Prod_Prg_Mas Group_Prod_Prg_Mas { get; set; }
    }
}
