//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotSplitMas
    {
        public LotSplitMas()
        {
            this.LotSplitDet = new HashSet<LotSplitDet>();
        }
    
        public int LotSplitMasId { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string TransNo { get; set; }
        public string EntryNo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string RefNo { get; set; }
        public string SplitType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ICollection<LotSplitDet> LotSplitDet { get; set; }
    }
}
