//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkEnqMas
    {
        public MarkEnqMas()
        {
            this.MarkEnqFabric = new HashSet<MarkEnqFabric>();
            this.MarkEnqItemDet = new HashSet<MarkEnqItemDet>();
            this.MarkEnqStyle = new HashSet<MarkEnqStyle>();
            this.MarkEnqEmbPrint = new HashSet<MarkEnqEmbPrint>();
            this.MarkQuoteMas = new HashSet<MarkQuoteMas>();
            this.MarkQuoteMas1 = new HashSet<MarkQuoteMas>();
        }
    
        public int EnquiryId { get; set; }
        public string EnquiryNo { get; set; }
        public Nullable<System.DateTime> EnqDate { get; set; }
        public int CompanyId { get; set; }
        public int BuyerId { get; set; }
        public string BuyerRef { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public int TermsId { get; set; }
        public Nullable<System.DateTime> DespDate { get; set; }
        public string Remarks { get; set; }
        public string Despatched_closed { get; set; }
        public string Sampling { get; set; }
        public string Ordered { get; set; }
        public string Status { get; set; }
        public Nullable<int> ShipSystemId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual OrderBuyer Buyer { get; set; }
        public virtual ICollection<MarkEnqFabric> MarkEnqFabric { get; set; }
        public virtual ICollection<MarkEnqItemDet> MarkEnqItemDet { get; set; }
        public virtual ICollection<MarkEnqStyle> MarkEnqStyle { get; set; }
        public virtual ICollection<MarkEnqEmbPrint> MarkEnqEmbPrint { get; set; }
        public virtual OrderCompany Company { get; set; }
        public virtual ICollection<MarkQuoteMas> MarkQuoteMas { get; set; }
        public virtual ICollection<MarkQuoteMas> MarkQuoteMas1 { get; set; }
    }
}
