//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkQuoteYarn
    {
        public int Markquoteyarnid { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public int FabID { get; set; }
        public int Itemid { get; set; }
        public int Sizeid { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> CostPerKG { get; set; }
        public Nullable<int> ComponentId { get; set; }
    
        public virtual OrderItem Item { get; set; }
        public virtual OrderSize Size { get; set; }
        public virtual MarkQuoteMas MarkQuoteMas { get; set; }
    }
}
