//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MasterEntities : DbContext
    {
        public MasterEntities()
            : base("name=MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddLess> AddLess { get; set; }
        public DbSet<Agent> Agent { get; set; }
        public DbSet<Approval> Approval { get; set; }
        public DbSet<Bank> Bank { get; set; }
        public DbSet<BuyerCharges> BuyerCharges { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<ColorCode> ColorCode { get; set; }
        public DbSet<ColorGroup> ColorGroup { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<CompanyUnit> CompanyUnit { get; set; }
        public DbSet<Consignee> Consignee { get; set; }
        public DbSet<Courier> Courier { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Designation> Designation { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<FabricMaster> FabricMaster { get; set; }
        public DbSet<FabricProcess> FabricProcess { get; set; }
        public DbSet<FabricYarn> FabricYarn { get; set; }
        public DbSet<Acc_Gsttaxmaster> Acc_Gsttaxmaster { get; set; }
        public DbSet<Acc_HSNMaster> Acc_HSNMaster { get; set; }
        public DbSet<Followup> Followup { get; set; }
        public DbSet<Garment_Uom> Garment_Uom { get; set; }
        public DbSet<Item_Rate> Item_Rate { get; set; }
        public DbSet<ItemGroup> ItemGroup { get; set; }
        public DbSet<Ledger> Ledger { get; set; }
        public DbSet<MerchTeamBuyer> MerchTeamBuyer { get; set; }
        public DbSet<MerchTeamEmployee> MerchTeamEmployee { get; set; }
        public DbSet<MerchTeamMas> MerchTeamMas { get; set; }
        public DbSet<Mode_Of_Shipment> Mode_Of_Shipment { get; set; }
        public DbSet<Commercialmas> Commercialmas { get; set; }
        public DbSet<Payment_Terms> Payment_Terms { get; set; }
        public DbSet<PortofLoading> PortofLoading { get; set; }
        public DbSet<ProcessSetup> ProcessSetup { get; set; }
        public DbSet<Reason> Reason { get; set; }
        public DbSet<SampleTypeMaster> SampleTypeMaster { get; set; }
        public DbSet<Season> Season { get; set; }
        public DbSet<ShipmentSystem> ShipmentSystem { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<StoreSection> StoreSection { get; set; }
        public DbSet<StoreUnit> StoreUnit { get; set; }
        public DbSet<Style> Style { get; set; }
        public DbSet<Style_Group> Style_Group { get; set; }
        public DbSet<StyleDetail> StyleDetail { get; set; }
        public DbSet<StyleHeader> StyleHeader { get; set; }
        public DbSet<StyleTempDet> StyleTempDet { get; set; }
        public DbSet<StyleTempMas> StyleTempMas { get; set; }
        public DbSet<TermDet> TermDet { get; set; }
        public DbSet<TermMas> TermMas { get; set; }
        public DbSet<TestingType> TestingType { get; set; }
        public DbSet<Unit_Conversion> Unit_Conversion { get; set; }
        public DbSet<UserGroup> UserGroup { get; set; }
        public DbSet<WorkDivision> WorkDivision { get; set; }
        public DbSet<Item> Item { get; set; }
        public DbSet<Size> Size { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<Unit_of_measurement> Unit_of_measurement { get; set; }
        public DbSet<Emp_Store_Setup> Emp_Store_Setup { get; set; }
        public DbSet<Username> Username { get; set; }
        public DbSet<MasterProcess> Process { get; set; }
        public DbSet<Description> Description { get; set; }
        public DbSet<Buyer> Buyer { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<SupplierProcessSetup> SupplierProcessSetup { get; set; }
    
        public virtual ObjectResult<Proc_Apparel_GetAccountsMasterCheck_Result> Proc_Apparel_GetAccountsMasterCheck(Nullable<int> addlessId)
        {
            var addlessIdParameter = addlessId.HasValue ?
                new ObjectParameter("AddlessId", addlessId) :
                new ObjectParameter("AddlessId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetAccountsMasterCheck_Result>("Proc_Apparel_GetAccountsMasterCheck", addlessIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetAgentMasterCheck_Result> Proc_Apparel_GetAgentMasterCheck(Nullable<int> agentid)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetAgentMasterCheck_Result>("Proc_Apparel_GetAgentMasterCheck", agentidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetBuyerChargesdet_Result> Proc_Apparel_GetBuyerChargesdet(Nullable<int> buyid)
        {
            var buyidParameter = buyid.HasValue ?
                new ObjectParameter("Buyid", buyid) :
                new ObjectParameter("Buyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetBuyerChargesdet_Result>("Proc_Apparel_GetBuyerChargesdet", buyidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetBuyerChargesMainGrid_Result> Proc_Apparel_GetBuyerChargesMainGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetBuyerChargesMainGrid_Result>("Proc_Apparel_GetBuyerChargesMainGrid");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetBuyerMasterCheck_Result> Proc_Apparel_GetBuyerMasterCheck(Nullable<int> buyerid)
        {
            var buyeridParameter = buyerid.HasValue ?
                new ObjectParameter("buyerid", buyerid) :
                new ObjectParameter("buyerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetBuyerMasterCheck_Result>("Proc_Apparel_GetBuyerMasterCheck", buyeridParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetBuyerWiseItemMainDetails_Result> Proc_Apparel_GetBuyerWiseItemMainDetails(Nullable<int> buyerId, Nullable<int> itemId, Nullable<int> colorId, Nullable<int> sizeId, Nullable<int> supplierId)
        {
            var buyerIdParameter = buyerId.HasValue ?
                new ObjectParameter("BuyerId", buyerId) :
                new ObjectParameter("BuyerId", typeof(int));
    
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var colorIdParameter = colorId.HasValue ?
                new ObjectParameter("ColorId", colorId) :
                new ObjectParameter("ColorId", typeof(int));
    
            var sizeIdParameter = sizeId.HasValue ?
                new ObjectParameter("SizeId", sizeId) :
                new ObjectParameter("SizeId", typeof(int));
    
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetBuyerWiseItemMainDetails_Result>("Proc_Apparel_GetBuyerWiseItemMainDetails", buyerIdParameter, itemIdParameter, colorIdParameter, sizeIdParameter, supplierIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCityMasterCheck_Result> Proc_Apparel_GetCityMasterCheck(Nullable<int> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCityMasterCheck_Result>("Proc_Apparel_GetCityMasterCheck", cityIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetColorMasterCheck_Result> Proc_Apparel_GetColorMasterCheck(Nullable<int> colorid)
        {
            var coloridParameter = colorid.HasValue ?
                new ObjectParameter("colorid", colorid) :
                new ObjectParameter("colorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetColorMasterCheck_Result>("Proc_Apparel_GetColorMasterCheck", coloridParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCompUnitMasterCheck_Result> Proc_Apparel_GetCompUnitMasterCheck(Nullable<int> unitid)
        {
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCompUnitMasterCheck_Result>("Proc_Apparel_GetCompUnitMasterCheck", unitidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCountryMasterCheck_Result> Proc_Apparel_GetCountryMasterCheck(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCountryMasterCheck_Result>("Proc_Apparel_GetCountryMasterCheck", countryIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCurrencyMasterCheck_Result> Proc_Apparel_GetCurrencyMasterCheck(Nullable<int> currencyId)
        {
            var currencyIdParameter = currencyId.HasValue ?
                new ObjectParameter("CurrencyId", currencyId) :
                new ObjectParameter("CurrencyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCurrencyMasterCheck_Result>("Proc_Apparel_GetCurrencyMasterCheck", currencyIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetDepartMasterCheck_Result> Proc_Apparel_GetDepartMasterCheck(Nullable<int> deprtId)
        {
            var deprtIdParameter = deprtId.HasValue ?
                new ObjectParameter("DeprtId", deprtId) :
                new ObjectParameter("DeprtId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetDepartMasterCheck_Result>("Proc_Apparel_GetDepartMasterCheck", deprtIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetDesgMasterCheck_Result> Proc_Apparel_GetDesgMasterCheck(Nullable<int> desgId)
        {
            var desgIdParameter = desgId.HasValue ?
                new ObjectParameter("DesgId", desgId) :
                new ObjectParameter("DesgId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetDesgMasterCheck_Result>("Proc_Apparel_GetDesgMasterCheck", desgIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetEmployeeMasterCheck_Result> Proc_Apparel_GetEmployeeMasterCheck(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetEmployeeMasterCheck_Result>("Proc_Apparel_GetEmployeeMasterCheck", employeeIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetFabricMasterEditDet_Result> Proc_Apparel_GetFabricMasterEditDet(Nullable<int> masid, Nullable<int> fabricid)
        {
            var masidParameter = masid.HasValue ?
                new ObjectParameter("Masid", masid) :
                new ObjectParameter("Masid", typeof(int));
    
            var fabricidParameter = fabricid.HasValue ?
                new ObjectParameter("Fabricid", fabricid) :
                new ObjectParameter("Fabricid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetFabricMasterEditDet_Result>("Proc_Apparel_GetFabricMasterEditDet", masidParameter, fabricidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetFabricProcessEditDet_Result> Proc_Apparel_GetFabricProcessEditDet(Nullable<int> masid)
        {
            var masidParameter = masid.HasValue ?
                new ObjectParameter("Masid", masid) :
                new ObjectParameter("Masid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetFabricProcessEditDet_Result>("Proc_Apparel_GetFabricProcessEditDet", masidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetFabricYarnEditDet_Result> Proc_Apparel_GetFabricYarnEditDet(Nullable<int> masid)
        {
            var masidParameter = masid.HasValue ?
                new ObjectParameter("Masid", masid) :
                new ObjectParameter("Masid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetFabricYarnEditDet_Result>("Proc_Apparel_GetFabricYarnEditDet", masidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetYarnwiseFabricDet_Result> Proc_Apparel_GetYarnwiseFabricDet(Nullable<int> itemid, Nullable<int> colorid, Nullable<int> sizeid)
        {
            var itemidParameter = itemid.HasValue ?
                new ObjectParameter("itemid", itemid) :
                new ObjectParameter("itemid", typeof(int));
    
            var coloridParameter = colorid.HasValue ?
                new ObjectParameter("colorid", colorid) :
                new ObjectParameter("colorid", typeof(int));
    
            var sizeidParameter = sizeid.HasValue ?
                new ObjectParameter("sizeid", sizeid) :
                new ObjectParameter("sizeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetYarnwiseFabricDet_Result>("Proc_Apparel_GetYarnwiseFabricDet", itemidParameter, coloridParameter, sizeidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCSIGSTDetails_Result> Proc_Apparel_GetCSIGSTDetails(string hsncode)
        {
            var hsncodeParameter = hsncode != null ?
                new ObjectParameter("Hsncode", hsncode) :
                new ObjectParameter("Hsncode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCSIGSTDetails_Result>("Proc_Apparel_GetCSIGSTDetails", hsncodeParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetGarmUomMasterCheck_Result> Proc_Apparel_GetGarmUomMasterCheck(Nullable<int> gUomid)
        {
            var gUomidParameter = gUomid.HasValue ?
                new ObjectParameter("GUomid", gUomid) :
                new ObjectParameter("GUomid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetGarmUomMasterCheck_Result>("Proc_Apparel_GetGarmUomMasterCheck", gUomidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetItemgroupMasterCheck_Result> Proc_Apparel_GetItemgroupMasterCheck(Nullable<int> itemgroupid)
        {
            var itemgroupidParameter = itemgroupid.HasValue ?
                new ObjectParameter("itemgroupid", itemgroupid) :
                new ObjectParameter("itemgroupid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetItemgroupMasterCheck_Result>("Proc_Apparel_GetItemgroupMasterCheck", itemgroupidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetItemMasterCheck_Result> Proc_Apparel_GetItemMasterCheck(Nullable<int> itemid)
        {
            var itemidParameter = itemid.HasValue ?
                new ObjectParameter("itemid", itemid) :
                new ObjectParameter("itemid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetItemMasterCheck_Result>("Proc_Apparel_GetItemMasterCheck", itemidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetItemRateDetEdit_Result> Proc_Apparel_GetItemRateDetEdit(Nullable<int> buyid, Nullable<int> rateId)
        {
            var buyidParameter = buyid.HasValue ?
                new ObjectParameter("buyid", buyid) :
                new ObjectParameter("buyid", typeof(int));
    
            var rateIdParameter = rateId.HasValue ?
                new ObjectParameter("RateId", rateId) :
                new ObjectParameter("RateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetItemRateDetEdit_Result>("Proc_Apparel_GetItemRateDetEdit", buyidParameter, rateIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetMainItemList_Result> Proc_Apparel_GetMainItemList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetMainItemList_Result>("Proc_Apparel_GetMainItemList");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetMainLoadItemRate_Result> Proc_Apparel_GetMainLoadItemRate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetMainLoadItemRate_Result>("Proc_Apparel_GetMainLoadItemRate");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetPayModeMasterCheck_Result> Proc_Apparel_GetPayModeMasterCheck(Nullable<int> mode_of_Shipmentid)
        {
            var mode_of_ShipmentidParameter = mode_of_Shipmentid.HasValue ?
                new ObjectParameter("Mode_of_Shipmentid", mode_of_Shipmentid) :
                new ObjectParameter("Mode_of_Shipmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetPayModeMasterCheck_Result>("Proc_Apparel_GetPayModeMasterCheck", mode_of_ShipmentidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_BaseProgramType_Result> Proc_Apparel_BaseProgramType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_BaseProgramType_Result>("Proc_Apparel_BaseProgramType");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetPaymentTermsMasterCheck_Result> Proc_Apparel_GetPaymentTermsMasterCheck(Nullable<int> pay_Termid)
        {
            var pay_TermidParameter = pay_Termid.HasValue ?
                new ObjectParameter("Pay_Termid", pay_Termid) :
                new ObjectParameter("Pay_Termid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetPaymentTermsMasterCheck_Result>("Proc_Apparel_GetPaymentTermsMasterCheck", pay_TermidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetPortOFLoadingMasterCheck_Result> Proc_Apparel_GetPortOFLoadingMasterCheck(Nullable<int> portId)
        {
            var portIdParameter = portId.HasValue ?
                new ObjectParameter("PortId", portId) :
                new ObjectParameter("PortId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetPortOFLoadingMasterCheck_Result>("Proc_Apparel_GetPortOFLoadingMasterCheck", portIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetProcessMasterCheck_Result> Proc_Apparel_GetProcessMasterCheck(Nullable<int> processId)
        {
            var processIdParameter = processId.HasValue ?
                new ObjectParameter("ProcessId", processId) :
                new ObjectParameter("ProcessId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetProcessMasterCheck_Result>("Proc_Apparel_GetProcessMasterCheck", processIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetProSeqSetProcessLoad_Result> Proc_Apparel_GetProSeqSetProcessLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetProSeqSetProcessLoad_Result>("Proc_Apparel_GetProSeqSetProcessLoad");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetProSeqSetSeqenceLoad_Result> Proc_Apparel_GetProSeqSetSeqenceLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetProSeqSetSeqenceLoad_Result>("Proc_Apparel_GetProSeqSetSeqenceLoad");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetShipMasterCheck_Result> Proc_Apparel_GetShipMasterCheck(Nullable<int> systemId)
        {
            var systemIdParameter = systemId.HasValue ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetShipMasterCheck_Result>("Proc_Apparel_GetShipMasterCheck", systemIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetSizeMasterCheck_Result> Proc_Apparel_GetSizeMasterCheck(Nullable<int> sizeid)
        {
            var sizeidParameter = sizeid.HasValue ?
                new ObjectParameter("Sizeid", sizeid) :
                new ObjectParameter("Sizeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetSizeMasterCheck_Result>("Proc_Apparel_GetSizeMasterCheck", sizeidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetMainStyleList_Result> Proc_Apparel_GetMainStyleList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetMainStyleList_Result>("Proc_Apparel_GetMainStyleList");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetStoreUnitMasterCheck_Result> Proc_Apparel_GetStoreUnitMasterCheck(Nullable<int> storeid)
        {
            var storeidParameter = storeid.HasValue ?
                new ObjectParameter("storeid", storeid) :
                new ObjectParameter("storeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetStoreUnitMasterCheck_Result>("Proc_Apparel_GetStoreUnitMasterCheck", storeidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetStyleMasterCheck_Result> Proc_Apparel_GetStyleMasterCheck(Nullable<int> styleid)
        {
            var styleidParameter = styleid.HasValue ?
                new ObjectParameter("Styleid", styleid) :
                new ObjectParameter("Styleid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetStyleMasterCheck_Result>("Proc_Apparel_GetStyleMasterCheck", styleidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetStyleTemplate_Result> Proc_Apparel_GetStyleTemplate(Nullable<int> tempid)
        {
            var tempidParameter = tempid.HasValue ?
                new ObjectParameter("Tempid", tempid) :
                new ObjectParameter("Tempid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetStyleTemplate_Result>("Proc_Apparel_GetStyleTemplate", tempidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetSupplierMasterCheck_Result> Proc_Apparel_GetSupplierMasterCheck(Nullable<int> supplierid)
        {
            var supplieridParameter = supplierid.HasValue ?
                new ObjectParameter("supplierid", supplierid) :
                new ObjectParameter("supplierid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetSupplierMasterCheck_Result>("Proc_Apparel_GetSupplierMasterCheck", supplieridParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetTermTempEditdetails_Result> Proc_Apparel_GetTermTempEditdetails(Nullable<int> tempMasId)
        {
            var tempMasIdParameter = tempMasId.HasValue ?
                new ObjectParameter("TempMasId", tempMasId) :
                new ObjectParameter("TempMasId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetTermTempEditdetails_Result>("Proc_Apparel_GetTermTempEditdetails", tempMasIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetTermTempMaindetails_Result> Proc_Apparel_GetTermTempMaindetails(Nullable<int> tempMasId)
        {
            var tempMasIdParameter = tempMasId.HasValue ?
                new ObjectParameter("TempMasId", tempMasId) :
                new ObjectParameter("TempMasId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetTermTempMaindetails_Result>("Proc_Apparel_GetTermTempMaindetails", tempMasIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetGroupName_Result> Proc_Apparel_GetGroupName(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetGroupName_Result>("Proc_Apparel_GetGroupName", groupIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetUomMasterCheck_Result> Proc_Apparel_GetUomMasterCheck(Nullable<int> uomid)
        {
            var uomidParameter = uomid.HasValue ?
                new ObjectParameter("Uomid", uomid) :
                new ObjectParameter("Uomid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetUomMasterCheck_Result>("Proc_Apparel_GetUomMasterCheck", uomidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCityDetails_Result> Proc_Apparel_GetCityDetails(Nullable<int> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCityDetails_Result>("Proc_Apparel_GetCityDetails", cityIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetCompMasterCheck_Result> Proc_Apparel_GetCompMasterCheck(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetCompMasterCheck_Result>("Proc_Apparel_GetCompMasterCheck", companyIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetMainColorList_Result1> Proc_Apparel_GetMainColorList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetMainColorList_Result1>("Proc_Apparel_GetMainColorList");
        }
    
        public virtual int Proc_Apparel_ExceptionLogging(string exceptionMsg, string exceptionType, string exceptionSource, string exceptionURL)
        {
            var exceptionMsgParameter = exceptionMsg != null ?
                new ObjectParameter("ExceptionMsg", exceptionMsg) :
                new ObjectParameter("ExceptionMsg", typeof(string));
    
            var exceptionTypeParameter = exceptionType != null ?
                new ObjectParameter("ExceptionType", exceptionType) :
                new ObjectParameter("ExceptionType", typeof(string));
    
            var exceptionSourceParameter = exceptionSource != null ?
                new ObjectParameter("ExceptionSource", exceptionSource) :
                new ObjectParameter("ExceptionSource", typeof(string));
    
            var exceptionURLParameter = exceptionURL != null ?
                new ObjectParameter("ExceptionURL", exceptionURL) :
                new ObjectParameter("ExceptionURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Apparel_ExceptionLogging", exceptionMsgParameter, exceptionTypeParameter, exceptionSourceParameter, exceptionURLParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetMainStoreSetup_Result> Proc_Apparel_GetMainStoreSetup(Nullable<int> employeeid, Nullable<int> storeid)
        {
            var employeeidParameter = employeeid.HasValue ?
                new ObjectParameter("Employeeid", employeeid) :
                new ObjectParameter("Employeeid", typeof(int));
    
            var storeidParameter = storeid.HasValue ?
                new ObjectParameter("Storeid", storeid) :
                new ObjectParameter("Storeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetMainStoreSetup_Result>("Proc_Apparel_GetMainStoreSetup", employeeidParameter, storeidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_GetStoreUnitfromEmployee_Result> Proc_Apparel_GetStoreUnitfromEmployee(string userid, string storeType, Nullable<int> companyid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var storeTypeParameter = storeType != null ?
                new ObjectParameter("StoreType", storeType) :
                new ObjectParameter("StoreType", typeof(string));
    
            var companyidParameter = companyid.HasValue ?
                new ObjectParameter("Companyid", companyid) :
                new ObjectParameter("Companyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetStoreUnitfromEmployee_Result>("Proc_Apparel_GetStoreUnitfromEmployee", useridParameter, storeTypeParameter, companyidParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_StoreSetupAdd_Result> Proc_Apparel_StoreSetupAdd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_StoreSetupAdd_Result>("Proc_Apparel_StoreSetupAdd");
        }
    
        public virtual ObjectResult<Proc_Apparel_StoreSetupEdit_Result> Proc_Apparel_StoreSetupEdit(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_StoreSetupEdit_Result>("Proc_Apparel_StoreSetupEdit", employeeIdParameter);
        }
    
        public virtual ObjectResult<Proc_Apparel_StoreSetupEmployee_Result> Proc_Apparel_StoreSetupEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_StoreSetupEmployee_Result>("Proc_Apparel_StoreSetupEmployee");
        }
    
        public virtual ObjectResult<Proc_Apparel_StoreSetupStoreddl_Result> Proc_Apparel_StoreSetupStoreddl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_StoreSetupStoreddl_Result>("Proc_Apparel_StoreSetupStoreddl");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetSizeEditSeqList_Result> Proc_Apparel_GetSizeEditSeqList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetSizeEditSeqList_Result>("Proc_Apparel_GetSizeEditSeqList");
        }
    
        public virtual ObjectResult<Proc_Apparel_GetMasterdescriptionLoad_Result> Proc_Apparel_GetMasterdescriptionLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Apparel_GetMasterdescriptionLoad_Result>("Proc_Apparel_GetMasterdescriptionLoad");
        }
    }
}
