//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisPathSize
    {
        public int SizeId { get; set; }
        public string size1 { get; set; }
        public string Item_Type { get; set; }
        public string lookup { get; set; }
        public decimal ActualSize { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
