//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSalesInvoiceMas
    {
        public OrderSalesInvoiceMas()
        {
            this.OrderSalesInvoiceAddless = new HashSet<OrderSalesInvoiceAddless>();
            this.OrderSalesInvoiceDet = new HashSet<OrderSalesInvoiceDet>();
        }
    
        public int Invid { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> buyerid { get; set; }
        public Nullable<int> conssigneeid { get; set; }
        public Nullable<int> notify { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public string refno { get; set; }
        public Nullable<System.DateTime> refdate { get; set; }
        public Nullable<int> portofloading { get; set; }
        public Nullable<int> destination { get; set; }
        public Nullable<int> portofdischarge { get; set; }
        public Nullable<int> shipmode { get; set; }
        public Nullable<int> systemid { get; set; }
        public Nullable<int> payment { get; set; }
        public string Precarriage { get; set; }
        public Nullable<int> placeofrecpt { get; set; }
        public string Vesselno { get; set; }
        public string MarksNos { get; set; }
        public Nullable<decimal> Totalcartons { get; set; }
        public Nullable<decimal> Totalgrosswgt { get; set; }
        public Nullable<decimal> Totalnetwgt { get; set; }
        public Nullable<int> currencyid { get; set; }
        public Nullable<decimal> Exrate { get; set; }
        public string SBillNo { get; set; }
        public Nullable<System.DateTime> SBillDate { get; set; }
        public string CTDNo { get; set; }
        public Nullable<System.DateTime> CTDDate { get; set; }
        public string LCNo { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public string LCtype { get; set; }
        public string Statement { get; set; }
        public string StatementCode { get; set; }
        public string StatementType { get; set; }
        public string SchemeCode { get; set; }
        public string ContainerNo { get; set; }
    
        public virtual ICollection<OrderSalesInvoiceAddless> OrderSalesInvoiceAddless { get; set; }
        public virtual ICollection<OrderSalesInvoiceDet> OrderSalesInvoiceDet { get; set; }
    }
}
