//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Cancel_mas
    {
        public Process_Cancel_mas()
        {
            this.Process_Cancel_det = new HashSet<Process_Cancel_det>();
        }
    
        public int Process_Cancel_masid { get; set; }
        public string process_Cancel_no { get; set; }
        public Nullable<System.DateTime> process_Cancel_date { get; set; }
        public string Cancel_Ref_no { get; set; }
        public Nullable<System.DateTime> Cancel_Ref_date { get; set; }
        public string Remarks { get; set; }
        public string OrderType { get; set; }
        public string CancelOrClose { get; set; }
        public Nullable<int> proc_recpt_masid { get; set; }
    
        public virtual ICollection<Process_Cancel_det> Process_Cancel_det { get; set; }
    }
}
