//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GetStockTransferEntryItemDetails_Result3
    {
        public int StockId { get; set; }
        public string Item { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public int ItemID { get; set; }
        public int ColorID { get; set; }
        public int SizeID { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public string TransNo { get; set; }
        public int SupplierID { get; set; }
        public string Supplier { get; set; }
        public string Uom { get; set; }
        public int UomID { get; set; }
        public int ProcessId { get; set; }
        public string Process { get; set; }
        public decimal MRate { get; set; }
        public int storeunitid { get; set; }
        public Nullable<decimal> Prg_Qty { get; set; }
        public int PrgDetID { get; set; }
        public System.DateTime Stockdate { get; set; }
    }
}
