//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Inv_RateDiff
    {
        public int Process_inv_Rateid { get; set; }
        public Nullable<int> Process_Invid { get; set; }
        public string proc_recpt_no { get; set; }
        public Nullable<decimal> GrnAmt { get; set; }
        public Nullable<decimal> InvAmt { get; set; }
        public Nullable<decimal> RateDiff { get; set; }
        public Nullable<int> Proc_Recpt_detid { get; set; }
        public decimal QtyDiff { get; set; }
        public string IsChecked { get; set; }
    
        public virtual Process_Recpt_Det Process_Recpt_Det { get; set; }
        public virtual Process_Inv_Mas Process_Inv_Mas { get; set; }
    }
}
