//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GetCuttingReturnDetails_Result2
    {
        public string joborderno { get; set; }
        public int CuttingOrdid { get; set; }
        public string CuttingOrderNo { get; set; }
        public int CutIssid { get; set; }
        public string CutIssNo { get; set; }
        public Nullable<System.DateTime> CuttingIssueDate { get; set; }
        public string OrderType { get; set; }
        public string Processor { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Style { get; set; }
    }
}
