//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GetProcessInvPrnOrderEditDetails_Result2
    {
        public Nullable<int> process_invid { get; set; }
        public int Process_InvDetid { get; set; }
        public Nullable<int> Proc_Recpt_Detid { get; set; }
        public string Job_ord_No { get; set; }
        public Nullable<int> Process_Inv_JobDetID { get; set; }
        public Nullable<decimal> invoiceQty { get; set; }
        public Nullable<decimal> Received_Qty { get; set; }
        public string RefNo { get; set; }
        public string OrderNo { get; set; }
        public string Style { get; set; }
        public Nullable<decimal> Rec_Rate { get; set; }
        public Nullable<long> SNo { get; set; }
        public int Proc_Recpt_JobDetid { get; set; }
        public bool IsValidateProcessOrdQty { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
    }
}
