//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Recpt_Return
    {
        public int Process_Recpt_Retid { get; set; }
        public Nullable<int> Process_Recpt_masid { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> ProcessOrdId { get; set; }
        public Nullable<int> Proc_Iss_Stockid { get; set; }
        public decimal Returnqty { get; set; }
        public decimal LossQty { get; set; }
        public Nullable<int> ProcessJobDetid { get; set; }
        public Nullable<int> ProcIssueJobId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Process_Recpt_Mas Process_Recpt_Mas { get; set; }
        public virtual Process_Ord_Mas Process_Ord_Mas { get; set; }
    }
}
