//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Inv_AddLess
    {
        public Nullable<int> Process_Invid { get; set; }
        public int Process_Inv_AddLessid { get; set; }
        public Nullable<int> AddLessid { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string aorl { get; set; }
    
        public virtual Process_Inv_Mas Process_Inv_Mas { get; set; }
    }
}
