//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessSeq_Mas_Amend
    {
        public ProcessSeq_Mas_Amend()
        {
            this.ProcessSeq_Amend = new HashSet<ProcessSeq_Amend>();
        }
    
        public int AmdProc_seq_masid { get; set; }
        public string Job_ord_no { get; set; }
        public string OrderType { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ICollection<ProcessSeq_Amend> ProcessSeq_Amend { get; set; }
    }
}
