//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GetPurchaseInvEntryOrdDetails_Result2
    {
        public Nullable<decimal> received_qty { get; set; }
        public string OrdNo { get; set; }
        public string refno { get; set; }
        public string style { get; set; }
        public Nullable<int> styleid { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> sizeid { get; set; }
        public int Grn_DetId { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<long> SNo { get; set; }
        public Nullable<decimal> Excess_Qty { get; set; }
        public Nullable<decimal> Rejqty { get; set; }
    }
}
