//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GProcessLoadMainGrid_Result1
    {
        public int procordid { get; set; }
        public string Closed { get; set; }
        public string ProcessorType { get; set; }
        public string type { get; set; }
        public string processorder { get; set; }
        public Nullable<System.DateTime> ProcessOrdate { get; set; }
        public Nullable<System.DateTime> DelidateTime { get; set; }
        public string Process { get; set; }
        public int Processid { get; set; }
        public string Company { get; set; }
        public string CompanyName { get; set; }
        public int Companyid { get; set; }
        public int Id { get; set; }
        public string CompanyUnit { get; set; }
        public string Ordertype { get; set; }
        public string Processor { get; set; }
        public int ProcessorId { get; set; }
        public string remarks { get; set; }
        public int StoreUnitId { get; set; }
    }
}
