//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GetReturnInnerDetailForEdit_Result1
    {
        public string Remarks { get; set; }
        public string Item { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public int Itemid { get; set; }
        public int Colorid { get; set; }
        public int Sizeid { get; set; }
        public Nullable<decimal> Balanceqty { get; set; }
        public decimal Issueqty { get; set; }
        public int CuttingIssueDetid { get; set; }
        public int CuttingReturnDetid { get; set; }
        public string RetLocation { get; set; }
        public int RetLocationID { get; set; }
        public decimal Lossqty { get; set; }
        public decimal Returnqty { get; set; }
        public string RetLocType { get; set; }
        public decimal Allotedqty { get; set; }
        public string UOM { get; set; }
        public string LotNo { get; set; }
        public int CuttingIssueStockid { get; set; }
        public Nullable<decimal> CancelQty { get; set; }
        public Nullable<decimal> SecQty { get; set; }
    }
}
