//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    
    public partial class Proc_Apparel_GetPurchaseInvEditDetails_Result1
    {
        public int pur_invid { get; set; }
        public string invoice_no { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public int company_id { get; set; }
        public Nullable<int> company_unitid { get; set; }
        public Nullable<int> supplierid { get; set; }
        public Nullable<decimal> Gross_amount { get; set; }
        public Nullable<decimal> Addless_amount { get; set; }
        public Nullable<decimal> invoice_value { get; set; }
        public string supp_inv_no { get; set; }
        public Nullable<System.DateTime> supp_inv_date { get; set; }
        public string remarks { get; set; }
        public string ThroughDcInv { get; set; }
        public string commitcancel { get; set; }
        public Nullable<int> CreditID { get; set; }
        public Nullable<int> DebitID { get; set; }
        public Nullable<decimal> Payment_Amt { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<bool> Passed { get; set; }
        public string DebtRaised { get; set; }
        public string Approved { get; set; }
        public Nullable<int> ledgerid { get; set; }
        public Nullable<int> voucherid { get; set; }
        public string AddLessManualOrFormula { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string EWayNo { get; set; }
        public Nullable<System.DateTime> EWayDate { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> BillPassDate { get; set; }
        public string company { get; set; }
        public string supplier { get; set; }
        public int Debit_CreditID { get; set; }
        public string Head { get; set; }
        public decimal CAmt { get; set; }
        public decimal DAmt { get; set; }
        public string Reason { get; set; }
        public bool passedd { get; set; }
    }
}
