//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Recpt_Return
    {
        public int Production_Recpt_Retid { get; set; }
        public Nullable<int> Production_Recpt_masid { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> ProcessOrdId { get; set; }
        public Nullable<int> Prod_Iss_Stockid { get; set; }
        public decimal Returnqty { get; set; }
        public decimal LossQty { get; set; }
        public Nullable<int> ProcessJobDetid { get; set; }
        public Nullable<int> ProdIssueJobId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Prod_iss_JobDet Prod_iss_JobDet { get; set; }
        public virtual Production_Ord_Mas Production_Ord_Mas { get; set; }
    }
}
