//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionInvoiceMas
    {
        public ProductionInvoiceMas()
        {
            this.ProductionInvoiceDc = new HashSet<ProductionInvoiceDc>();
            this.ProductionInvoiceOrdDet = new HashSet<ProductionInvoiceOrdDet>();
            this.ProductionInvoiceRateDiff = new HashSet<ProductionInvoiceRateDiff>();
            this.ProductionInvoiceDet = new HashSet<ProductionInvoiceDet>();
            this.ProductionInvoiceAddless = new HashSet<ProductionInvoiceAddless>();
        }
    
        public int ProdInvid { get; set; }
        public string OrderType { get; set; }
        public string InvNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public decimal InvAmount { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Remarks { get; set; }
        public decimal PaymentAmt { get; set; }
        public string Paid { get; set; }
        public string Passed { get; set; }
        public Nullable<int> Processorid { get; set; }
        public Nullable<int> Processid { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string InvoiceType { get; set; }
        public string InternalOrExternal { get; set; }
        public Nullable<int> CompanyUnitId { get; set; }
        public string Approved { get; set; }
        public Nullable<int> voucherid { get; set; }
        public Nullable<int> ledgerid { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Saccode { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> TotCGST { get; set; }
        public Nullable<decimal> TotSGST { get; set; }
        public Nullable<decimal> TotIGST { get; set; }
        public string EWayNo { get; set; }
        public Nullable<System.DateTime> EWayDate { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> BillPassDate { get; set; }
        public string DebtRaised { get; set; }
    
        public virtual ICollection<ProductionInvoiceDc> ProductionInvoiceDc { get; set; }
        public virtual ICollection<ProductionInvoiceOrdDet> ProductionInvoiceOrdDet { get; set; }
        public virtual ICollection<ProductionInvoiceRateDiff> ProductionInvoiceRateDiff { get; set; }
        public virtual ICollection<ProductionInvoiceDet> ProductionInvoiceDet { get; set; }
        public virtual ICollection<ProductionInvoiceAddless> ProductionInvoiceAddless { get; set; }
    }
}
