//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionWorkDivision
    {
        public int WorkDivisionId { get; set; }
        public string WorkDivision1 { get; set; }
        public Nullable<int> Inchargeid { get; set; }
        public Nullable<int> Unitid { get; set; }
        public string DivisionType { get; set; }
        public bool IsActive { get; set; }
    }
}
