//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Recpt_Det
    {
        public Production_Recpt_Det()
        {
            this.Production_Recpt_JobDet = new HashSet<Production_Recpt_JobDet>();
        }
    
        public int Prod_Recpt_Detid { get; set; }
        public Nullable<int> Prod_Recpt_Masid { get; set; }
        public Nullable<int> ProcessOrdId { get; set; }
        public int itemid { get; set; }
        public int sizeid { get; set; }
        public int colorid { get; set; }
        public decimal Received_qty { get; set; }
        public decimal Sec_Qty { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> Invoice_Qty { get; set; }
        public string closed { get; set; }
        public Nullable<decimal> IPMarkup_rate { get; set; }
        public Nullable<decimal> OPMarkup_Rate { get; set; }
        public Nullable<int> IssuedSizeID { get; set; }
        public Nullable<decimal> WasQty { get; set; }
    
        public virtual Production_Ord_Mas Production_Ord_Mas { get; set; }
        public virtual ICollection<Production_Recpt_JobDet> Production_Recpt_JobDet { get; set; }
        public virtual Production_Recpt_Mas Production_Recpt_Mas { get; set; }
    }
}
