//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Recpt_Stock
    {
        public int RecptStockId { get; set; }
        public int RecptID { get; set; }
        public int RecptDetID { get; set; }
        public string BundleNo { get; set; }
        public int StockID { get; set; }
        public decimal RecptQty { get; set; }
        public decimal InvQty { get; set; }
        public string Closed { get; set; }
    }
}
