//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample_Ord_PlanDet
    {
        public Nullable<int> SPlanid { get; set; }
        public int SPlanDetid { get; set; }
        public Nullable<int> Itemid { get; set; }
        public Nullable<int> Colorid { get; set; }
        public Nullable<int> Sizeid { get; set; }
        public Nullable<int> UOMid { get; set; }
        public decimal Quantity { get; set; }
        public decimal App_Qty { get; set; }
        public decimal Issued_Qty { get; set; }
        public string ItemRemarks { get; set; }
        public Nullable<int> PurUomid { get; set; }
        public decimal BOMQty { get; set; }
        public Nullable<decimal> ToPurUOM { get; set; }
        public Nullable<bool> OCNClose { get; set; }
    
        public virtual Sample_Ord_PlanMas Sample_Ord_PlanMas { get; set; }
        public virtual PlanningColor Color { get; set; }
        public virtual PlanningUnit_of_measurement Unit_of_measurement { get; set; }
        public virtual PlanningUnit_of_measurement Unit_of_measurement1 { get; set; }
    }
}
