//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTranStock
    {
        public int TransferStkId { get; set; }
        public int TransferId { get; set; }
        public Nullable<int> TransferDetid { get; set; }
        public int FromStockId { get; set; }
        public Nullable<decimal> TransQty { get; set; }
        public Nullable<decimal> Markup_Rate { get; set; }
        public Nullable<int> NEWSTOCKID { get; set; }
    
        public virtual ItemStock ItemStock { get; set; }
        public virtual ItemStock ItemStock1 { get; set; }
    }
}
