//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonApparel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleHeader
    {
        public StyleHeader()
        {
            this.StyleDetail = new HashSet<StyleDetail>();
        }
    
        public int StyleId { get; set; }
        public string Style { get; set; }
        public string ArticleNo { get; set; }
        public string Season { get; set; }
        public string DesignName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Itemid { get; set; }
    
        public virtual ICollection<StyleDetail> StyleDetail { get; set; }
    }
}
