CREATE TABLE [dbo].[Cost_Defn_Bom_First]
(
	Cost_defn_bom_firstid  [int] IDENTITY(1,1) NOT NULL primary key,
	[Cost_Defn_id] [int] NOT NULL,
	[Cost_Defn_BOMid] [int] NULL,
	[Processid] [int] NULL,
	[Itemid] [int] NULL,
	[ColorID] [int] NULL,
	[SizeID] [int] NULL,
	[Quantity] [numeric](18, 0) NULL DEFAULT (0),
	[Rate] [numeric](15, 5) NOT NULL DEFAULT (0),
	[UOMID] [int] NULL,
	[Access_Type] [varchar](1) NULL,
	[Actual_Qty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[Actual_Rate] [numeric](15, 5) NOT NULL DEFAULT (0),
	[CurrencyId] [int] NULL,
	[ExRate] [numeric](15, 5) NOT NULL,
	[CurrencyRate] [numeric](15, 5) NOT NULL,
	[AppRate] [numeric](15, 5) NOT NULL,
	[AppCurrencyRate] [numeric](15, 5) NOT NULL,
	[DisplayOption] [char](1) NULL,
	[AppQty] [numeric](18, 0) NULL,
	[lUpdateDate] [datetime] NULL,
	CMCost numeric(15, 5) NULL,
	FinPer numeric(5, 2) NULL,
	MarkUpvalue numeric(15, 4) NULL,
	Gaficharges numeric(15, 4) NULL,
	Qizcharges numeric(15, 4) NULL,

	CONSTRAINT [fk_Cost_Defn_Bom_First_colorid] FOREIGN KEY([ColorID]) REFERENCES [dbo].[color] ([colorid]),
	CONSTRAINT [fk_Cost_Defn_Bom_First_itemid] FOREIGN KEY([Itemid]) REFERENCES [dbo].[Item] ([itemid]),
	CONSTRAINT [fk_Cost_Defn_Bom_First_processid] FOREIGN KEY([Processid]) REFERENCES [dbo].[Process] ([ProcessId]),
	CONSTRAINT [fk_Cost_Defn_Bom_First_sizeid] FOREIGN KEY([SizeID]) REFERENCES [dbo].[size] ([sizeid]),
	CONSTRAINT [fk_Cost_Defn_Bom_First_UOMid] FOREIGN KEY([UOMID]) REFERENCES [dbo].[Unit_of_measurement] ([uomid]),

)
