using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AxonApparel.Domain
{
    public class MisSetting
    {
        public int MisId { get; set; }
        public string path { get; set; }
        public string docupath { get; set; }
        public int dCompanyUnitId { get; set; }
        public int dCompanyId { get; set; }
        public int dCurrenyId { get; set; }
        public string dCAbs { get; set; }
        public string CompanyUnit { get; set; }
        public string Company { get; set; }
        public string reportpath { get; set; }
        public string FilterRefNo { get; set; }
        public int Inrid { get; set; }
        public string F7Option { get; set; }
        public string SupressZeroInNumGen { get; set; }
        public string CostAppCheck { get; set; }
        public string CostBudDetailsCheck { get; set; }
        public bool plan_fabric_sum_unit { get; set; }
        public string Popserver { get; set; }
        public string Fromid { get; set; }
        public char AllowGenStk { get; set; }
        public char CostProCheckWork { get; set; }
        public char AllowOrdQtyInvoice { get; set; }
        public char DisAccPackAttachinPO { get; set; }
        public decimal StockAuditExcessPer { get; set; }
        public char PurDocStd { get; set; }
        public string ASPdocpath { get; set; }
        public string AlertPODate { get; set; }
        public string MasterDeletion { get; set; }
        public string JobOrderCaption { get; set; }
        public Nullable<System.DateTime> ScriptUpdatedOn { get; set; }
        public char ProdPrgRndOff { get; set; }
        public int SelKeyCode { get; set; }
        public bool GotoNxtCntl { get; set; }
        public int markupstockid { get; set; }
        public bool GENDESCNEEDED { get; set; }
        public char ChkQltyIssue { get; set; }
        public char ChkIssueStock { get; set; }
        public char InwardNoMust { get; set; }
        public string ChkGRNAllowance { get; set; }
        public string ChkPOAllowance { get; set; }
        public char ALLOWEXCSQTYAGAINSTORDER { get; set; }
        public char IsBuyDateChecked { get; set; }
        public DateTime ChkBuyDate { get; set; }
        public char ChkNominatedSupplier { get; set; }
        public char ShowBuyerLookUp { get; set; }
        public string ChkSimilarPONumber { get; set; }
        public string AllowDamageStk { get; set; }
        public string IndividualProcNum { get; set; }
        public string ValidateGsminPostBom { get; set; }
        public string LotNoPrefix { get; set; }
        public int LotNoStartFrom { get; set; }
        public char MerchandiserWiseOrder { get; set; }
        public char ChkQltyInGrn { get; set; }
        public int DefaultSupplierId { get; set; }
        public char AllowonlyFDLStkInCutIss { get; set; }
        public char AllowSaveInOrdCumIssInCutt { get; set; }
        public char ChkRateInGenPO { get; set; }
        public char AllowonlyCDLStkInSewIss { get; set; }
        public char ShowProfitLossInBudgetQry { get; set; }
        public char ValidateIOinSewingRecpt { get; set; }
        public char CostAppCheckForSample { get; set; }
        public char ChkManualQtyAlwnceinWrkOrder { get; set; }
        public char ChkPrgQtyForStkTransfer { get; set; }
        public char ChkInvAppforBillPass { get; set; }
        public char ValidateIOinProdGenRecpt { get; set; }
        public char ValidateStkInoutInPO { get; set; }
        public char GenSampleDespno { get; set; }
        public char ValidateAppForOpenPrg { get; set; }
        public char ValidateQuotAppRateInBudget { get; set; }
        public char AllowActiveInSuplierMas { get; set; }
        public char validateReqDateinPO { get; set; }
        public char ValidateStkOnlyOutInPO { get; set; }
        public string FinYearCode { get; set; }
        public string TallyPath { get; set; }
        public string TallyExport { get; set; }
        public char ChkCustomerContour { get; set; }
        public string GenLotNoInProcess { get; set; }
        public int FromDays { get; set; }
        public string chkQltyInGeneralGRN { get; set; }
        public string ChkAutoLoadInCutRecpt { get; set; }
        public string chkTermsConditionsInPO { get; set; }
        public string ProcessOrderComboFilter { get; set; }
        public string ShowFabricOption { get; set; }
        public char AllowOrderGrouping { get; set; }
        public string IncludeCuttingInGenProd { get; set; }
        public string ValidatePOApproval { get; set; }
        public string ValidatePOAgIndent { get; set; }
        public string ValidateBudgetRateInCuttingOrder { get; set; }
        public string ValidateBudgetRateGenProdIssue { get; set; }
        public string ValidateBudgetRateSewing { get; set; }
        public string ValidateBudgetRateInLineIss { get; set; }
        public string EvaluteIssueReceiptUOMInProdSummaryRpt { get; set; }
        public char AllowProgPrgPosting { get; set; }
        public string ASP_ActualPath { get; set; }
        public int pur_managerid { get; set; }
        public int KGS_UOM { get; set; }
        public int PCS_UOM { get; set; }
        public string AssortColumnCaption { get; set; }
        public int EMailSMSRefresh { get; set; }
        public char ShowPrintToolBarInMis { get; set; }
        public int AlertBeforeDays { get; set; }
        public string ApplicationPath { get; set; }
        public string Merchand_OnlyTA { get; set; }
        public string ShowAdditional_InFabricPlanning { get; set; }
        public string WinPrintFont { get; set; }
        public string WinPrintFontSize { get; set; }
        public string PrintFooterAtEnd { get; set; }
        public int RestrictPrinting { get; set; }
        public string OrderProcess_ShowMerchandiserOnly { get; set; }
        public string PrintTINNo { get; set; }
        public string LoadTAMonitorOnStartup { get; set; }
        public string ShowMerchandiserTeamwiseOrdersOnly { get; set; }
        public int RejectAlertPercentage { get; set; }
        public string IsShipmentwiseAllowance { get; set; }
        public char chkgeninout { get; set; }
        public char joborderallowance { get; set; }
        public bool AlertForStockAge { get; set; }
        public bool POApproval { get; set; }
        public bool ValidateJobOrderApproval { get; set; }
        public bool ValidateProcessOrderApproval { get; set; }
        public bool ValidateStore { get; set; }
        public bool AlertProcessOrderEMail { get; set; }
        public bool ValidateProcessStore { get; set; }
        public bool ChkBOMStoreIssue { get; set; }
        public bool IncludeSewingInGenProd { get; set; }
        public bool ValidateProductionStore { get; set; }
        public bool ChkStyleColor { get; set; }
        public char CostProCheckSample { get; set; }
        public bool ShipmentwiseProduction { get; set; }
        public bool ChkSISProdAccIssue { get; set; }
        public bool StylewiseJoborder { get; set; }
        public int LicencecompanyID { get; set; }
        public char LicenceExpiryDate { get; set; }
        public string Todate { get; set; }
        public string Fromdate { get; set; }
        public char LicenceType { get; set; }
        public string Licenceusers { get; set; }
        public string NoOfUser { get; set; }
        public string ASSTYEAR { get; set; }
        public bool ProductionProgramAllowance { get; set; }
        public bool ALLOWMANUALPRODUCTIONPROGRAM { get; set; }
        public bool AllowCompanyPrefixDup { get; set; }
        public bool CheckGRNInvoiceNo { get; set; }
        public bool ChkInvoiceAgainstGrn { get; set; }
        public bool ValidatePlanningApproval { get; set; }
        public string SupplierLotPrefix { get; set; }
        public bool ValidateZeroRateInReProcess { get; set; }
        public bool ValidateProgramSize { get; set; }
        public bool ValidateCompanyStore { get; set; }
        public bool EnableTransactionDate { get; set; }
        public bool ValidateIssQtyonlyforProcRetrn { get; set; }
        public bool OpenPrgProcessAllowance { get; set; }
        public bool EnableJJFormInProcess { get; set; }
        public bool CheckSupplierBudgetinPurchase { get; set; }
        public bool CheckSupplierBudgetinProcess { get; set; }
        public string FINYEAR { get; set; }
        public bool GenerateFinYearNumber { get; set; }
        public bool checkBillsToInvoiceEntry { get; set; }
        public bool DisableProdTranDate { get; set; }
        public bool ChkProInvoiceAgainstQuality { get; set; }
        public bool PoUnit { get; set; }
        public char UpdateActRateFromInvRate { get; set; }
        public char DontAllowProcessProgram { get; set; }
        public char EnableAutoMailforPO { get; set; }
        public char UnitStockUpdation { get; set; }
        public bool ChkcuttingAllowance { get; set; }
        public bool ChkSewingAllowance { get; set; }
        public decimal CuttingAllowanceQty { get; set; }
        public decimal SewingAllowanceQty { get; set; }
        public bool ChkDespatch { get; set; }
        public decimal DespatchQty { get; set; }
        public char chkItemComp { get; set; }
        public string ShowDateTime { get; set; }
        public char AllowGMSPieceinCutReceipt { get; set; }
        public char ChkListIteminPurchase { get; set; }
        public int ChkPOPrintingRestrict { get; set; }
        public char ChkQltyInProcessGRN { get; set; }
        public bool ChkInvoiceagainstProcessGRN { get; set; }
        public bool GPOApproval { get; set; }
        public bool CHEKEXCLUDEINVOICE { get; set; }
        public bool CHEKEXCLUDE_PRN_INVOICE { get; set; }
        public char AllowExcessinBuyerDispatch { get; set; }
        public char ManualPostPurchaseInvoiceActuals { get; set; }
        public decimal CuttingOrderAllowanceQty { get; set; }
        public bool ChkCutOrdAllowance { get; set; }
        public char ChkAppReqForAccPUR { get; set; }
        public bool BoxItemStock { get; set; }
        public bool chkStoreIssueSplNo { get; set; }
        public string ValidateZeroRateInReProduction { get; set; }
        public string ShwApproveinOrderStatus { get; set; }
        public string showStyleInOrderPro { get; set; }
        public bool validatebomqtyindelivery { get; set; }
        public string enablejjforminproduction { get; set; }
        public bool EnableJJFormInStores { get; set; }
        public char ValidateInvoiceMarkuprate { get; set; }
        public string chkitemremarks { get; set; }
        public char chkissueprintlocation { get; set; }
        public char allowexcesspurchaseinvoiceqty { get; set; }
        public char validategrnmarkuprate { get; set; }
        public char chkblankdate { get; set; }
        public char defaultappload { get; set; }
        public int chkOrd_Sample { get; set; }
        public int ChkPurInvRateWithBudgetRate { get; set; }
        public int chkPrsGrnRateInvRate { get; set; }
        public int chkProdGrnRateInvRate { get; set; }
        public int ValidateDCTemplate { get; set; }
        public bool CHKAllowExcessProductionInvoice { get; set; }
        public char chkPoprintFooter { get; set; }
        public bool chkValidateSupplierApproval { get; set; }
        public bool ValidateMarkupRateinSubStoreReceipt { get; set; }
        public string validateSupplierApproval { get; set; }
        public string chkValidateVerifyBeforeApproval { get; set; }
        public char chk_poeditloadwithoutorder { get; set; }
        public char ChkPoBalHighlighting { get; set; }
        public char CHKPRODGRNQTYINVQTY { get; set; }
        public char validateStyleschedulesize { get; set; }
        public char ChkSupTinPanValidation { get; set; }
        public char ValidateHSNCode { get; set; }
        public char validateGSTENTRY { get; set; }
        public char chkpoprintGST { get; set; }
        public char ChkPoprintGSTSPLREQ { get; set; }
        public char ValidateGstEntrySplReq { get; set; }
        public bool CHKBUNDLENOVALIDATION { get; set; }
        public char ValidateProcsGSTEntry { get; set; }
        public char ValidateProdnGSTEntry { get; set; }
        public char ValidateProdncompGSTEntry { get; set; }
        public int Validate_InvoiceRateChange { get; set; }
        public char CHKLOGGENERLAACCPLAAING { get; set; }
        public char Validatecuttingorderissue { get; set; }
        public bool chkAllowanceValidationAccPlanning { get; set; }
        public int LotNoMustInGeneralProduction { get; set; }
        public int chkAllowOrderedTrims { get; set; }
        public char chkpoprintgstspreq { get; set; }
        public bool ChkProductionInterlPrintLog { get; set; }
        public string ValidateGafiCharges { get; set; }
        public string chkGstPerAgainstHsncode { get; set; }
        public string chkEnbAssortRate { get; set; }
        public bool chkEnbTransDate { get; set; }        
        public string chkBuyerWiseCosting { get; set; }
        public string ChkJobOrderRate { get; set; }
        public Nullable<int> BaseColorid { get; set; }
        public bool ValidateBudRateinPurinvBulk { get; set; }
        public bool ValidateBudRateinPurinvSample { get; set; }
        public bool ValidateBudRateinProinvBulk { get; set; }
        public bool ValidateBudRateinProinvSample { get; set; }
        public decimal CuttingTolerance { get; set; }

        public string ValidateBudgetRateGenProdIssueSample { get; set; }
        public string ValidateBudgetRateSewingSample { get; set; }
        public string ValidateBudgetRateInCuttingOrderSample { get; set; }
        public string checkBillsToInvoiceEntryProduction { get; set; }

        public string CostAppSamPurCheck { get; set; }
        public string CostAppSamProCheck { get; set; }
        public string chkSalesInvoiceDespatch { get; set; }

        public string Avatar_Gender { get; set; }
        public bool checkBillsToComInvoiceEntry { get; set; }
        public bool ValidatePurchaseGRNqty { get; set; }
        public bool ValidateProcessGRNqty { get; set; }
        public string chkFabricDeliveryIssue { get; set; }
        public bool chkValidateProgramQtyinTransfer { get; set; }
        public int ChkLicenceexpiry { get; set; }
        public bool ValidateProcessIssueLoc { get; set; }
        public bool validateProcessOrderApp { get; set; }
        public bool SupplierSetup { get; set; }

        public string chkBarcode { get; set; }
        public string chkQRcode { get; set; }

    }



}
