CREATE TABLE [dbo].[Report_Footer_Setup]
(
	[Rpt_Setupid] [int] IDENTITY(1,1) NOT NULL Primary key,
	[Doc_Title] [varchar](100) NULL,
	[Rpt_Title] [varchar](100) NULL,
	[Rpt_StdCode] [varchar](20) NULL,
	[Rpt_Buyer] [bit] NULL,
	[Rpt_BuyLookup] [bit] NULL,
	[Rpt_Orderno] [bit] NULL,
	[Rpt_Style] [bit] NULL,
	[Rpt_StyleQty] [bit] NULL,
	[Rpt_JobNo] [bit] NULL,
	[Rpt_RefNo] [bit] NULL,
	[Rpt_forwarded] [varchar](25) NULL,
	[Rpt_Verified] [varchar](25) NULL,
	[Rpt_Prepared] [varchar](25) NULL,
	[Rpt_Approved] [varchar](25) NULL,
	[Rpt_Remarks] [varchar](1500) NULL,
	[rpt_Header] [varchar](1500) NULL,
	[HBolD] [bit] NULL,
	[merch] [int] NULL,
	[RPT_STDCODE2] [varchar](20) NULL,
	[voucherid] [int] NULL,
	[ledgerid] [int] NULL,
	[TallyExport] [varchar](1) NOT NULL CHECK  (([tallyexport] = 'Y' or [tallyExport] = 'N')) DEFAULT ('N'),
	[mail_Company] [bit] NOT NULL DEFAULT (0),
	[mail_ProductionUnit] [bit] NOT NULL DEFAULT (0),
	[mail_Supplier] [bit] NOT NULL DEFAULT (0),
	[mail_Buyer] [bit] NOT NULL DEFAULT (0),
	[mail_Employee] [bit] NOT NULL DEFAULT (0),
	[mail_Agent] [bit] NOT NULL DEFAULT (0),
	[mail_consignee] [bit] NOT NULL DEFAULT (0),
	[mail_Bank] [bit] NOT NULL DEFAULT (0),
	[mail_Courier] [bit] NOT NULL DEFAULT (0),
	[PrintCount] [int] NULL,
	[PrintMerchTeam] [bit] NOT NULL DEFAULT (0),
	[Rpt_BuyerRefNo] [bit] NULL,

	 CONSTRAINT [FK_report_option_ledger] FOREIGN KEY([ledgerid]) REFERENCES [dbo].[Ledger] ([LedgerId]),
	 CONSTRAINT [FK_report_option_voucher] FOREIGN KEY([voucherid]) REFERENCES [dbo].[Voucher] ([VoucherId])
)
