CREATE TABLE [dbo].[Company]
(
	[CompanyId] [int] IDENTITY(1,1) NOT NULL,
	[Company] [varchar](40) NOT NULL,
	[Company_Lookup] [varchar](10) NOT NULL,
	[Address1] [varchar](50) NULL,
	[Address2] [varchar](50) NULL,
	[Address3] [varchar](50) NULL,
	[CityId] [int] NULL,
	[CountryId] [int] NULL,
	[Zipcode] int NULL,
	[Mob_No] [numeric](15, 0) NOT NULL DEFAULT (''),
	[Fax] [varchar](30) NULL,
	[E_mail] [varchar](100) NULL DEFAULT (''),
	[Telex] [varchar](30) NULL,
	[RBI_CODE_No] int NULL,
	[IEcode] int NULL,
	[Aepc_No] int NULL,
	[Aepc_Date] [datetime] NULL,
	[Tngst_No] int NULL,
	[Cst_No] int NULL,
	[Cst_Date] [datetime] NULL,
	[Prefix] [varchar](3) NULL,
	[LogoName] [varchar](30) NULL,
	[Tin_no] int NULL,
	[Tin_Date] [datetime] NULL,
	[IsActive] [bit] NOT NULL DEFAULT (1),
	[EANNo] int NULL,
	[IECNo] int NULL,
	[RCMCNO] int NULL,
	[C_Range] [varchar](250) NULL,
	[C_Division] [varchar](250) NULL,
	[ContactName] [varchar](100) NULL,
	[BaseCurrencyId][int] Null,
	[GSTNo] [varchar](50) NULL,
    CONSTRAINT [PK_Company] PRIMARY KEY ([CompanyId]), 
	CONSTRAINT [FK_Company_City] FOREIGN KEY (CityId) REFERENCES [City]([Id]), 
	CONSTRAINT [FK_Company_Country] FOREIGN KEY (CountryId) REFERENCES [Country]([countryid]),
	CONSTRAINT [FK_Company_Currency] FOREIGN KEY (BaseCurrencyId) REFERENCES [Currency]([CurrencyId])
	
)

