CREATE TABLE [dbo].[ItemStock]
(
	[StockId] [int] IDENTITY(1,1) NOT NULL,
	[UnitId] [int] NULL,
	[Itemid] [int] NULL,
	[Colorid] [int] NULL,
	[sizeid] [int] NULL,
	[qty] [numeric](14, 3) NOT NULL,
	[Rate] [numeric](14, 4) NULL,
	[joborderNo] [varchar](20) NULL,
	[TransType] [varchar](5) NULL,
	[Transno] [varchar](20) NOT NULL,
	[alloted] [numeric](14, 3) NULL,
	[ItemCat] [varchar](2) NULL,
	[processId] [int] NULL,
	[sQty] [numeric](12, 3) NULL,
	[lotNo] [varchar](20) NULL,
	[balQty] [numeric](14, 3) NULL,
	[purorprod] [char](2) NULL,
	[transdate] [datetime] NULL,
	[companyid] [int] NULL,
	[supplierid] [int] NULL,
	[return_qty] [numeric](14, 3) NULL,
	[uomid] [int] NULL,
	[MfrId] [int] NULL,
	[Styleid] [int] NULL,
	[unit_or_other] [varchar](1) NULL,
	[ReProg] [varchar](1) NULL,
	[StockType] [varchar](1) NULL DEFAULT ('S'),
	[Remarks] [varchar](1000) NULL,
	[Markup_Rate] [numeric](14, 4) NULL DEFAULT 0,
	[CatType] [varchar](3) NOT NULL DEFAULT (''),
	[GuomId] [int] NULL,
	[ItemCode] [varchar](30) NOT NULL DEFAULT (''),
	[BundleNo] [varchar](12) NOT NULL DEFAULT (''),
	[OrderIdent] [varchar](50) NULL,
	[FabricGSM] [varchar](30) NOT NULL DEFAULT (''),
	[StoreUnitID] [int] NULL,
	[SectionID] [int] NULL,
	[StockDate] [datetime] NULL,
	[ShipRowId] [int] NULL,
	[BARCODE] [varchar](25) NULL,
	[slno] [varchar](25) NULL,
	Buy_ord_Ship varchar NULL,
	GSM [decimal] (4,0) null,
	BatchNo varchar(20) null,
	SkuNo varchar(50) null,
	CONSTRAINT [PK_StockId] PRIMARY KEY ([StockId]),
	--CONSTRAINT [fk_Buy_ord_Buy_ord_Ship] FOREIGN KEY([ShipRowId]) REFERENCES [dbo].[Buy_ord_Ship] ([ShipRowId]),
	CONSTRAINT [fk_GuomId_ref] FOREIGN KEY([GuomId]) REFERENCES [dbo].[Garment_UOM] ([GUOMid]),
	CONSTRAINT [fk_StoreSectionId_ref] FOREIGN KEY([SectionID]) REFERENCES [dbo].[StoreSection] ([SectionId]),
	CONSTRAINT [fk_StoreUnitId_ref] FOREIGN KEY([StoreUnitID]) REFERENCES [dbo].[StoreUnit] ([StoreunitId]),
	CONSTRAINT [Fk_ItemStock_Colorid] FOREIGN KEY([Colorid]) REFERENCES [dbo].[color] ([colorid]),
	CONSTRAINT [Fk_ItemStock_Itemid] FOREIGN KEY([Itemid]) REFERENCES [dbo].[Item] ([itemid]),
	CONSTRAINT [Fk_ItemStock_Sizeid] FOREIGN KEY([sizeid]) REFERENCES [dbo].[size] ([sizeid]), 
    CONSTRAINT [CK_ItemStock_alloted] CHECK (([Alloted] >= 0)),
	CONSTRAINT [CK_ItemStock_balQty] CHECK (([balQty] >= 0)),
	CONSTRAINT [CK_ItemStock_qty] CHECK (([qty] >= 0)),
	CONSTRAINT [CK_ItemStock_Transno] CHECK (([TransNo] <> ''))


)
