CREATE TABLE [dbo].[Item]
(
	[ItemId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Item] NVARCHAR(250) NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1,
	ItemGroupId int null,
	Bas_Unit int null,
	Pur_Unit int null,
	Sec_Unit int null,
	ItemType varchar(30) null,
	Descript varchar(30) null,
	CGST numeric(19,3) null,
	SGST numeric(19,3) null,
	IGST numeric(19,3) null,
	HSNCODE varchar(50) null,
	Itemrate [numeric](14, 3)  NULL,
	Item_Cat [varchar](1)  NULL,
	lookup [varchar](10)  NULL,
	ColorOth [varchar](1)  NULL,
	conv_factor [numeric](5, 3)  NULL,
	Percentage varchar(2) NULL,
	Allow_Value [numeric](15, 5)  NULL,
	ColorNo [varchar](50)  NULL,
	GSTTaxCode [varchar](10) null,
	IGSTTaxCode [varchar](10) null,
	MajComp char(1) null,
	[MinQty] [numeric](19, 3) null,
	[MaxQty] [numeric](19, 3) null,
	CONSTRAINT [FK_Item_ToItemGroup] FOREIGN KEY ([ItemGroupId]) REFERENCES [ItemGroup]([Id]),
	CONSTRAINT [FK_BasUOMRef] FOREIGN KEY (Bas_Unit) REFERENCES Unit_of_measurement(UomId),
	CONSTRAINT [Pur_Unit] FOREIGN KEY([Pur_unit]) REFERENCES [dbo].[Unit_of_measurement] (UomId),
	CONSTRAINT [Sec_Unit] FOREIGN KEY([Sec_Unit]) REFERENCES [dbo].[Unit_of_measurement] (UomId)

)
