CREATE TABLE [dbo].[Process_Ord_Det]
(
	[processorddetid] [int] IDENTITY(1,1) NOT NULL primary key,
	[processordid] [int] NULL,
	[itemid] [int] NULL,
	[colorid] [int] NULL,
	[sizeid] [int] NULL,
	[inp_op] [varchar](1) NULL CHECK  (([inp_op] = 'O' or [inp_op] = 'I')),
	[order_output_qty] [numeric](14, 3) NOT NULL  DEFAULT (0.000),
	[issued_qty] [numeric](14, 3) NOT NULL  DEFAULT (0.000),
	[rate] [numeric](15, 5) NULL,
	[received_qty] [numeric](14, 3) NOT NULL  DEFAULT (0.000),
	[Return_Qty] [numeric](14, 3) NULL  DEFAULT (0.000),
	[Damage_qty] [numeric](14, 3) NULL  DEFAULT (0.000),
	[Cancel_Qty] [numeric](14, 3) NULL  DEFAULT (0.000),
	[Returnable_Qty] [numeric](14, 3) NULL,
	[Inp_CancelQty] [numeric](14, 3) NULL,
	[Markup_Rate] [numeric](15, 5) NULL,
	[Markup_Value] [numeric](15, 5) NULL,
	[PlannedSizeID] [int] NULL,
	[OrdSecQty] [numeric](14, 3) NOT NULL DEFAULT (0),
	[ItemRemarks] [varchar](200) NOT NULL  DEFAULT (''),
	[Loss_Qty] [numeric](14, 3) NULL DEFAULT (0.000),
	[IN_OUT_UOMID] [int] NULL DEFAULT (null),
	[IssueSizeID] [int] NULL,
	[ReqDate] [datetime] NULL,
	[Loop_Len] [varchar](100) NULL,
	[Gauge] [varchar](100) NULL,
	[TaxAppVal] [numeric](15, 3) NULL,
	[FinDiaid] [int] NULL,
	[FinGsm] [numeric](15, 3) NULL,
	OpItemId int null,
	OpColorId int null,
	OpSizeId int null,
	CONSTRAINT [FK_Proc_ord_det_ColorId] FOREIGN KEY([colorid]) REFERENCES [dbo].[Color] ([Colorid]),
	CONSTRAINT [FK_Proc_ord_det_ItemId] FOREIGN KEY([itemid]) REFERENCES [dbo].[Item] ([ItemId]),
	CONSTRAINT [FK_Proc_ord_det_plannedSizeId] FOREIGN KEY([PlannedSizeID]) REFERENCES [dbo].[Size] ([SizeId]),
	 CONSTRAINT [FK_Proc_ord_det_SizeId] FOREIGN KEY([sizeid]) REFERENCES [dbo].[Size] ([SizeId]),
	 CONSTRAINT [FK_Proc_ord_det_FinDiaid] FOREIGN KEY([FinDiaid]) REFERENCES [dbo].[Size] ([SizeId]),
	 CONSTRAINT [FK_Proc_ord_det_processordid] FOREIGN KEY([processordid])REFERENCES [dbo].[Process_Ord_Mas] ([processordid])
)
