CREATE TABLE [dbo].[Process_Inv_Mas]
(
	[Process_Invid] [int] IDENTITY(1,1) NOT NULL, 
	[OrderType] [varchar](1) NULL,
	[Inv_No] [varchar](20) NOT NULL,
	[Inv_Date] [datetime] NULL,
	[Inv_Amount] [numeric](12, 2) NULL,
	[Entry_No] [varchar](20) NULL,
	[Entry_Date] [datetime] NULL,
	[Remarks] [varchar](1000) NULL,
	[Payment_Amt] [numeric](15, 5) NOT NULL DEFAULT (0),
	[Paid] [bit] NULL,
	[Passed] [bit] NULL,
	[DebitCredit] [char](1) NULL,
	[DebtRaised] [varchar](1) NULL DEFAULT ('N'),
	[Approved] [char](1) NOT NULL DEFAULT ('N'),
	[ledgerid] [int] NULL,
	[SupplierId] [int] NOT NULL DEFAULT (0),
	[InternalOrExternal] [varchar](1) NOT NULL DEFAULT ('E'),
	[voucherid] [int] NULL,
	[CreatedBy] [int] NULL,
	[ApprovedBy] [int] NULL,
	[MultiFlag] [char](1) NULL,
	[TotSGST] [numeric](18, 3) NULL,
	[TotIGST] [numeric](18, 3) NULL,
	[Saccode] [varchar](50) NULL,
	[TotCGST] [numeric](18, 3) NULL,
	[CGST] [numeric](18, 3) NULL,
	[SGST] [numeric](18, 3) NULL,
	[IGST] [numeric](18, 3) NULL,
	[EWayNo] [varchar](25) NULL,
	[EWayDate] [date] NULL,
    CONSTRAINT [PK_Process_Inv_Mas] PRIMARY KEY ([Process_Invid]), 
    CONSTRAINT [FK_Process_Inv_Mas_Ledger] FOREIGN KEY ([ledgerid]) REFERENCES [Ledger]([LedgerId]),
	CONSTRAINT [FK_Process_Inv_Mas_Voucher] FOREIGN KEY ([voucherid]) REFERENCES [Voucher]([VoucherId]),
	CONSTRAINT [FK_Process_Inv_Mas_EmployeeCreated] FOREIGN KEY ([CreatedBy]) REFERENCES [employee]([employeeid]),
	CONSTRAINT [FK_Process_Inv_Mas_EmployeeApproved] FOREIGN KEY ([ApprovedBy]) REFERENCES [employee]([employeeid]), 
    CONSTRAINT [CK_Process_Inv_Mas_InternalOrExternal] CHECK (([InternalOrExternal] = 'I' or [InternalOrExternal] = 'E')),
	CONSTRAINT [CK_Process_Inv_Mas_Approved] CHECK (([Approved] = 'N' or [Approved] = 'Y')),
	CONSTRAINT [CK_Process_Inv_Mas_DebitCredit] CHECK (([DebitCredit] = 'N' or [DebitCredit] = 'Y')),
	CONSTRAINT [CK_Process_Inv_Mas_DebtRaised] CHECK (([DebtRaised] = 'N' or [DebtRaised] = 'Y')),
	CONSTRAINT [CK_Process_Inv_Mas_OrderType] CHECK (([OrderType]='J' OR [OrderType]='W' OR [OrderType]='S' OR [OrderType]='G' OR [OrderType]='L')),
    CONSTRAINT [CK_Process_Inv_Mas_Paid] CHECK (([Paid] = 0 or [Paid] = 1)),
    CONSTRAINT [CK_Process_Inv_Mas_Passed] CHECK (([Passed] = 0 or [Passed] = 1))
)
